edition = "2024";

package grafana.plugin.v3;

// GroupVersion represents the API group and version of a resource.
message GroupVersion {
  // The api group
  string group = 1;

  // version eg v1, v2beta1, etc
  string version = 2;
}

// GroupVersionKind identifies the properties of an object.
message GroupVersionKind {
  // The api group
  string group = 1;

  // version eg v1, v2beta1, etc
  string version = 2;

  // Kind name (capitalized singular)
  string kind = 3;
}

// GroupVersionKind identifies the properties of an object.
message GroupVersionResource {
  // The api group
  string group = 1;

  // version eg v1, v2beta1, etc
  string version = 2;

  // resource name (lowercase plural)
  string kind = 3;
}

// ResourceObject 
message ResourceObject {
  // For plugins, group is usually the plugin identifier
  GroupVersionResource type = 1;

  // tenant isolation
  string namespace = 3;

  // the identifier
  string name = 4;

  // the resource version -- changes here indicate that raw body has changed
  string rv = 5;

  // JSON raw resource
  bytes raw = 6;
}

// StringList is a list of strings. It is used as a map value, since protobuf
// does not allow a repeated value in a map directly.
message StringList {
  repeated string values = 1;
}