edition = "2024";

package grafana.plugin.v3;

import "grafana/plugin/v3/common.proto";

// RouteService enables HTTP-style requests over gRPC.
service RouteService {
  // CallRoute issues an HTTP-style request and streams the response back.
  rpc CallRoute(CallRouteRequest) returns (stream CallRouteResponse);
}

// RouteResource is the resource object referenced by the requested path
message RouteResource {
  // the parent resource type (eg, dashboards)
  string resource = 1;

  // The resource name when attached to a resource (ie, the route is a "subresource")
  string name = 2;

  // the resource version -- changes here indicate that raw body has changed
  string rv = 3;

  // JSON raw resource returned from `get`
  bytes raw = 4;
}

// CallRouteRequest is the request for RouteService.CallRoute.
message CallRouteRequest {
  // For plugins, group is usually the plugin identifier
  string group = 1;

  // version eg v1, v2beta1, etc
  string version = 2;

  // When namespaced
  string namespace = 3;

  // When the route is a sub-resource
  RouteResource parent = 4;

  // path relative to the configured location
  string path = 5;

  // method is the HTTP method.
  string method = 6;

  // url is the request URL.
  string url = 7;

  // headers are the raw HTTP request headers.
  map<string, StringList> headers = 8;

  // body is the raw HTTP request body.
  bytes body = 9;
}

// CallRouteResponse is a streamed chunk of the response for RouteService.CallRoute.
// The code and headers will only be used for the first stream chunk.
message CallRouteResponse {
  // code maps to raw HTTP status codes when passed over HTTP.
  int32 code = 1;

  // headers are the raw HTTP headers sent to the client.
  map<string, StringList> headers = 2;

  // body are the raw HTTP body bytes sent to the client.
  bytes body = 3;
}
