// EXPERIMENTAL: Plugin protocol v3 is a work in progress.
// The APIs and wire format may change or be removed without notice.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grafana/plugin/v3/conversion.proto

package pluginv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConversionService_ConvertObjects_FullMethodName = "/grafana.plugin.v3.ConversionService/ConvertObjects"
)

// ConversionServiceClient is the client API for ConversionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConversionService can be used to convert resources between versions.
// See: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-request-and-response
type ConversionServiceClient interface {
	// ConvertObjects converts objects to a target version.
	ConvertObjects(ctx context.Context, in *ConvertObjectsRequest, opts ...grpc.CallOption) (*ConvertObjectsResponse, error)
}

type conversionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConversionServiceClient(cc grpc.ClientConnInterface) ConversionServiceClient {
	return &conversionServiceClient{cc}
}

func (c *conversionServiceClient) ConvertObjects(ctx context.Context, in *ConvertObjectsRequest, opts ...grpc.CallOption) (*ConvertObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertObjectsResponse)
	err := c.cc.Invoke(ctx, ConversionService_ConvertObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversionServiceServer is the server API for ConversionService service.
// All implementations should embed UnimplementedConversionServiceServer
// for forward compatibility.
//
// ConversionService can be used to convert resources between versions.
// See: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-request-and-response
type ConversionServiceServer interface {
	// ConvertObjects converts objects to a target version.
	ConvertObjects(context.Context, *ConvertObjectsRequest) (*ConvertObjectsResponse, error)
}

// UnimplementedConversionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversionServiceServer struct{}

func (UnimplementedConversionServiceServer) ConvertObjects(context.Context, *ConvertObjectsRequest) (*ConvertObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertObjects not implemented")
}
func (UnimplementedConversionServiceServer) testEmbeddedByValue() {}

// UnsafeConversionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversionServiceServer will
// result in compilation errors.
type UnsafeConversionServiceServer interface {
	mustEmbedUnimplementedConversionServiceServer()
}

func RegisterConversionServiceServer(s grpc.ServiceRegistrar, srv ConversionServiceServer) {
	// If the following call panics, it indicates UnimplementedConversionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConversionService_ServiceDesc, srv)
}

func _ConversionService_ConvertObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversionServiceServer).ConvertObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConversionService_ConvertObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversionServiceServer).ConvertObjects(ctx, req.(*ConvertObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversionService_ServiceDesc is the grpc.ServiceDesc for ConversionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.v3.ConversionService",
	HandlerType: (*ConversionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertObjects",
			Handler:    _ConversionService_ConvertObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grafana/plugin/v3/conversion.proto",
}
