// EXPERIMENTAL: Plugin protocol v3 is a work in progress.
// The APIs and wire format may change or be removed without notice.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin/v3/admission.proto

package pluginv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdmissionService_AdmissionReview_FullMethodName = "/plugin.v3.AdmissionService/AdmissionReview"
)

// AdmissionServiceClient is the client API for AdmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.36.0/pkg/apis/admission/types.go#L41
type AdmissionServiceClient interface {
	// AdmissionReview validates and may mutate a resource.
	AdmissionReview(ctx context.Context, in *AdmissionReviewRequest, opts ...grpc.CallOption) (*AdmissionReviewResponse, error)
}

type admissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmissionServiceClient(cc grpc.ClientConnInterface) AdmissionServiceClient {
	return &admissionServiceClient{cc}
}

func (c *admissionServiceClient) AdmissionReview(ctx context.Context, in *AdmissionReviewRequest, opts ...grpc.CallOption) (*AdmissionReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmissionReviewResponse)
	err := c.cc.Invoke(ctx, AdmissionService_AdmissionReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmissionServiceServer is the server API for AdmissionService service.
// All implementations should embed UnimplementedAdmissionServiceServer
// for forward compatibility.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.36.0/pkg/apis/admission/types.go#L41
type AdmissionServiceServer interface {
	// AdmissionReview validates and may mutate a resource.
	AdmissionReview(context.Context, *AdmissionReviewRequest) (*AdmissionReviewResponse, error)
}

// UnimplementedAdmissionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdmissionServiceServer struct{}

func (UnimplementedAdmissionServiceServer) AdmissionReview(context.Context, *AdmissionReviewRequest) (*AdmissionReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdmissionReview not implemented")
}
func (UnimplementedAdmissionServiceServer) testEmbeddedByValue() {}

// UnsafeAdmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmissionServiceServer will
// result in compilation errors.
type UnsafeAdmissionServiceServer interface {
	mustEmbedUnimplementedAdmissionServiceServer()
}

func RegisterAdmissionServiceServer(s grpc.ServiceRegistrar, srv AdmissionServiceServer) {
	// If the following call panics, it indicates UnimplementedAdmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdmissionService_ServiceDesc, srv)
}

func _AdmissionService_AdmissionReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmissionReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionServiceServer).AdmissionReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdmissionService_AdmissionReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionServiceServer).AdmissionReview(ctx, req.(*AdmissionReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdmissionService_ServiceDesc is the grpc.ServiceDesc for AdmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v3.AdmissionService",
	HandlerType: (*AdmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdmissionReview",
			Handler:    _AdmissionService_AdmissionReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v3/admission.proto",
}
