// EXPERIMENTAL: Plugin protocol v3 is a work in progress.
// The APIs and wire format may change or be removed without notice.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v3/conversion.proto

package pluginv3

import (
	v1 "github.com/grafana/grafana-app-sdk/contracts/genproto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawObject contains a serialized resource and its kind.
type RawObject struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Gvk         *GroupVersionKind      `protobuf:"bytes,1,opt,name=gvk"`
	xxx_hidden_Raw         []byte                 `protobuf:"bytes,2,opt,name=raw"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,3,rep,name=warnings"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RawObject) Reset() {
	*x = RawObject{}
	mi := &file_plugin_v3_conversion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawObject) ProtoMessage() {}

func (x *RawObject) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_conversion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RawObject) GetGvk() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Gvk
	}
	return nil
}

func (x *RawObject) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *RawObject) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *RawObject) SetGvk(v *GroupVersionKind) {
	x.xxx_hidden_Gvk = v
}

func (x *RawObject) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RawObject) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *RawObject) HasGvk() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Gvk != nil
}

func (x *RawObject) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RawObject) ClearGvk() {
	x.xxx_hidden_Gvk = nil
}

func (x *RawObject) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Raw = nil
}

type RawObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// gvk identifies the object's kind.
	Gvk *GroupVersionKind
	// raw is the complete JSON-encoded object.
	Raw []byte
	// warnings contains non-fatal issues encountered during conversion.
	Warnings []string
}

func (b0 RawObject_builder) Build() *RawObject {
	m0 := &RawObject{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Gvk = b.Gvk
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Raw = b.Raw
	}
	x.xxx_hidden_Warnings = b.Warnings
	return m0
}

// ConvertObjectsRequest supports converting objects from one version to
// another.
type ConvertObjectsRequest struct {
	state                    protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Api           *GroupVersion                    `protobuf:"bytes,1,opt,name=api"`
	xxx_hidden_Uid           *string                          `protobuf:"bytes,2,opt,name=uid"`
	xxx_hidden_Objects       *[]*ConvertObjectsRequest_Object `protobuf:"bytes,3,rep,name=objects"`
	xxx_hidden_TargetVersion *string                          `protobuf:"bytes,4,opt,name=target_version,json=targetVersion"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConvertObjectsRequest) Reset() {
	*x = ConvertObjectsRequest{}
	mi := &file_plugin_v3_conversion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsRequest) ProtoMessage() {}

func (x *ConvertObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_conversion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsRequest) GetApi() *GroupVersion {
	if x != nil {
		return x.xxx_hidden_Api
	}
	return nil
}

func (x *ConvertObjectsRequest) GetUid() string {
	if x != nil {
		if x.xxx_hidden_Uid != nil {
			return *x.xxx_hidden_Uid
		}
		return ""
	}
	return ""
}

func (x *ConvertObjectsRequest) GetObjects() []*ConvertObjectsRequest_Object {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *ConvertObjectsRequest) GetTargetVersion() string {
	if x != nil {
		if x.xxx_hidden_TargetVersion != nil {
			return *x.xxx_hidden_TargetVersion
		}
		return ""
	}
	return ""
}

func (x *ConvertObjectsRequest) SetApi(v *GroupVersion) {
	x.xxx_hidden_Api = v
}

func (x *ConvertObjectsRequest) SetUid(v string) {
	x.xxx_hidden_Uid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ConvertObjectsRequest) SetObjects(v []*ConvertObjectsRequest_Object) {
	x.xxx_hidden_Objects = &v
}

func (x *ConvertObjectsRequest) SetTargetVersion(v string) {
	x.xxx_hidden_TargetVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ConvertObjectsRequest) HasApi() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Api != nil
}

func (x *ConvertObjectsRequest) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConvertObjectsRequest) HasTargetVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConvertObjectsRequest) ClearApi() {
	x.xxx_hidden_Api = nil
}

func (x *ConvertObjectsRequest) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Uid = nil
}

func (x *ConvertObjectsRequest) ClearTargetVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TargetVersion = nil
}

type ConvertObjectsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// api is the API group and version of the conversion request.
	Api *GroupVersion
	// uid is an identifier for the individual request/response. It allows
	// distinguishing instances of requests which are otherwise identical
	// (parallel requests, etc). It is meant to track the round trip between the
	// Kubernetes API server and the webhook, not the user request.
	Uid *string
	// objects contains the objects to convert.
	Objects []*ConvertObjectsRequest_Object
	// target_version is the version to convert to.
	TargetVersion *string
}

func (b0 ConvertObjectsRequest_builder) Build() *ConvertObjectsRequest {
	m0 := &ConvertObjectsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Api = b.Api
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Uid = b.Uid
	}
	x.xxx_hidden_Objects = &b.Objects
	if b.TargetVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_TargetVersion = b.TargetVersion
	}
	return m0
}

// ConvertObjectsResponse contains the converted objects.
type ConvertObjectsResponse struct {
	state                  protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Error       *v1.StatusResult                  `protobuf:"bytes,1,opt,name=error"`
	xxx_hidden_Uid         *string                           `protobuf:"bytes,2,opt,name=uid"`
	xxx_hidden_Converted   *[]*ConvertObjectsResponse_Object `protobuf:"bytes,3,rep,name=converted"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConvertObjectsResponse) Reset() {
	*x = ConvertObjectsResponse{}
	mi := &file_plugin_v3_conversion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsResponse) ProtoMessage() {}

func (x *ConvertObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_conversion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsResponse) GetError() *v1.StatusResult {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *ConvertObjectsResponse) GetUid() string {
	if x != nil {
		if x.xxx_hidden_Uid != nil {
			return *x.xxx_hidden_Uid
		}
		return ""
	}
	return ""
}

func (x *ConvertObjectsResponse) GetConverted() []*ConvertObjectsResponse_Object {
	if x != nil {
		if x.xxx_hidden_Converted != nil {
			return *x.xxx_hidden_Converted
		}
	}
	return nil
}

func (x *ConvertObjectsResponse) SetError(v *v1.StatusResult) {
	x.xxx_hidden_Error = v
}

func (x *ConvertObjectsResponse) SetUid(v string) {
	x.xxx_hidden_Uid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ConvertObjectsResponse) SetConverted(v []*ConvertObjectsResponse_Object) {
	x.xxx_hidden_Converted = &v
}

func (x *ConvertObjectsResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *ConvertObjectsResponse) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConvertObjectsResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *ConvertObjectsResponse) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Uid = nil
}

type ConvertObjectsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// error describes a failure to convert the requested objects.
	Error *v1.StatusResult
	// uid is an identifier for the individual request/response. This should be
	// copied over from the corresponding request.uid.
	Uid *string
	// converted contains the converted objects in the same order as the request.
	Converted []*ConvertObjectsResponse_Object
}

func (b0 ConvertObjectsResponse_builder) Build() *ConvertObjectsResponse {
	m0 := &ConvertObjectsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Error = b.Error
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Uid = b.Uid
	}
	x.xxx_hidden_Converted = &b.Converted
	return m0
}

// Object is a serialized object to convert.
type ConvertObjectsRequest_Object struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Gvk         *GroupVersionKind      `protobuf:"bytes,1,opt,name=gvk"`
	xxx_hidden_Raw         []byte                 `protobuf:"bytes,2,opt,name=raw"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConvertObjectsRequest_Object) Reset() {
	*x = ConvertObjectsRequest_Object{}
	mi := &file_plugin_v3_conversion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsRequest_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsRequest_Object) ProtoMessage() {}

func (x *ConvertObjectsRequest_Object) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_conversion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsRequest_Object) GetGvk() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Gvk
	}
	return nil
}

func (x *ConvertObjectsRequest_Object) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *ConvertObjectsRequest_Object) SetGvk(v *GroupVersionKind) {
	x.xxx_hidden_Gvk = v
}

func (x *ConvertObjectsRequest_Object) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConvertObjectsRequest_Object) HasGvk() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Gvk != nil
}

func (x *ConvertObjectsRequest_Object) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConvertObjectsRequest_Object) ClearGvk() {
	x.xxx_hidden_Gvk = nil
}

func (x *ConvertObjectsRequest_Object) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Raw = nil
}

type ConvertObjectsRequest_Object_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// gvk identifies the object's kind.
	Gvk *GroupVersionKind
	// raw is the complete JSON-encoded object.
	Raw []byte
}

func (b0 ConvertObjectsRequest_Object_builder) Build() *ConvertObjectsRequest_Object {
	m0 := &ConvertObjectsRequest_Object{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Gvk = b.Gvk
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Raw = b.Raw
	}
	return m0
}

// Object is a converted serialized object.
type ConvertObjectsResponse_Object struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Raw         []byte                 `protobuf:"bytes,1,opt,name=raw"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,2,rep,name=warnings"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConvertObjectsResponse_Object) Reset() {
	*x = ConvertObjectsResponse_Object{}
	mi := &file_plugin_v3_conversion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsResponse_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsResponse_Object) ProtoMessage() {}

func (x *ConvertObjectsResponse_Object) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_conversion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsResponse_Object) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *ConvertObjectsResponse_Object) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *ConvertObjectsResponse_Object) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConvertObjectsResponse_Object) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *ConvertObjectsResponse_Object) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConvertObjectsResponse_Object) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Raw = nil
}

type ConvertObjectsResponse_Object_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// raw is the complete JSON-encoded converted object.
	Raw []byte
	// warnings contains non-fatal issues encountered during conversion.
	Warnings []string
}

func (b0 ConvertObjectsResponse_Object_builder) Build() *ConvertObjectsResponse_Object {
	m0 := &ConvertObjectsResponse_Object{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Raw = b.Raw
	}
	x.xxx_hidden_Warnings = b.Warnings
	return m0
}

var File_plugin_v3_conversion_proto protoreflect.FileDescriptor

const file_plugin_v3_conversion_proto_rawDesc = "" +
	"\n" +
	"\x1aplugin/v3/conversion.proto\x12\tplugin.v3\x1a\x16plugin/v3/common.proto\x1a\x16common/v1/status.proto\"h\n" +
	"\tRawObject\x12-\n" +
	"\x03gvk\x18\x01 \x01(\v2\x1b.plugin.v3.GroupVersionKindR\x03gvk\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\x89\x02\n" +
	"\x15ConvertObjectsRequest\x12)\n" +
	"\x03api\x18\x01 \x01(\v2\x17.plugin.v3.GroupVersionR\x03api\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12A\n" +
	"\aobjects\x18\x03 \x03(\v2'.plugin.v3.ConvertObjectsRequest.ObjectR\aobjects\x12%\n" +
	"\x0etarget_version\x18\x04 \x01(\tR\rtargetVersion\x1aI\n" +
	"\x06Object\x12-\n" +
	"\x03gvk\x18\x01 \x01(\v2\x1b.plugin.v3.GroupVersionKindR\x03gvk\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\"\xd9\x01\n" +
	"\x16ConvertObjectsResponse\x12-\n" +
	"\x05error\x18\x01 \x01(\v2\x17.common.v1.StatusResultR\x05error\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12F\n" +
	"\tconverted\x18\x03 \x03(\v2(.plugin.v3.ConvertObjectsResponse.ObjectR\tconverted\x1a6\n" +
	"\x06Object\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings2j\n" +
	"\x11ConversionService\x12U\n" +
	"\x0eConvertObjects\x12 .plugin.v3.ConvertObjectsRequest\x1a!.plugin.v3.ConvertObjectsResponseB\xaf\x01\n" +
	"\rcom.plugin.v3B\x0fConversionProtoP\x01ZHgithub.com/grafana/grafana-app-sdk/contracts/genproto/plugin/v3;pluginv3\xa2\x02\x03PXX\xaa\x02\tPlugin.V3\xca\x02\tPlugin\\V3\xe2\x02\x15Plugin\\V3\\GPBMetadata\xea\x02\n" +
	"Plugin::V3b\beditionsp\xe9\a"

var file_plugin_v3_conversion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_v3_conversion_proto_goTypes = []any{
	(*RawObject)(nil),                     // 0: plugin.v3.RawObject
	(*ConvertObjectsRequest)(nil),         // 1: plugin.v3.ConvertObjectsRequest
	(*ConvertObjectsResponse)(nil),        // 2: plugin.v3.ConvertObjectsResponse
	(*ConvertObjectsRequest_Object)(nil),  // 3: plugin.v3.ConvertObjectsRequest.Object
	(*ConvertObjectsResponse_Object)(nil), // 4: plugin.v3.ConvertObjectsResponse.Object
	(*GroupVersionKind)(nil),              // 5: plugin.v3.GroupVersionKind
	(*GroupVersion)(nil),                  // 6: plugin.v3.GroupVersion
	(*v1.StatusResult)(nil),               // 7: common.v1.StatusResult
}
var file_plugin_v3_conversion_proto_depIdxs = []int32{
	5, // 0: plugin.v3.RawObject.gvk:type_name -> plugin.v3.GroupVersionKind
	6, // 1: plugin.v3.ConvertObjectsRequest.api:type_name -> plugin.v3.GroupVersion
	3, // 2: plugin.v3.ConvertObjectsRequest.objects:type_name -> plugin.v3.ConvertObjectsRequest.Object
	7, // 3: plugin.v3.ConvertObjectsResponse.error:type_name -> common.v1.StatusResult
	4, // 4: plugin.v3.ConvertObjectsResponse.converted:type_name -> plugin.v3.ConvertObjectsResponse.Object
	5, // 5: plugin.v3.ConvertObjectsRequest.Object.gvk:type_name -> plugin.v3.GroupVersionKind
	1, // 6: plugin.v3.ConversionService.ConvertObjects:input_type -> plugin.v3.ConvertObjectsRequest
	2, // 7: plugin.v3.ConversionService.ConvertObjects:output_type -> plugin.v3.ConvertObjectsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_v3_conversion_proto_init() }
func file_plugin_v3_conversion_proto_init() {
	if File_plugin_v3_conversion_proto != nil {
		return
	}
	file_plugin_v3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v3_conversion_proto_rawDesc), len(file_plugin_v3_conversion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v3_conversion_proto_goTypes,
		DependencyIndexes: file_plugin_v3_conversion_proto_depIdxs,
		MessageInfos:      file_plugin_v3_conversion_proto_msgTypes,
	}.Build()
	File_plugin_v3_conversion_proto = out.File
	file_plugin_v3_conversion_proto_goTypes = nil
	file_plugin_v3_conversion_proto_depIdxs = nil
}
