// EXPERIMENTAL: Plugin protocol v3 is a work in progress.
// The APIs and wire format may change or be removed without notice.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/v3/route.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteResource is the resource referenced by the requested subresource path.
type RouteResource struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resource    *string                `protobuf:"bytes,1,opt,name=resource"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Rv          *string                `protobuf:"bytes,3,opt,name=rv"`
	xxx_hidden_Raw         []byte                 `protobuf:"bytes,4,opt,name=raw"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RouteResource) Reset() {
	*x = RouteResource{}
	mi := &file_plugin_v3_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResource) ProtoMessage() {}

func (x *RouteResource) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RouteResource) GetResource() string {
	if x != nil {
		if x.xxx_hidden_Resource != nil {
			return *x.xxx_hidden_Resource
		}
		return ""
	}
	return ""
}

func (x *RouteResource) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RouteResource) GetRv() string {
	if x != nil {
		if x.xxx_hidden_Rv != nil {
			return *x.xxx_hidden_Rv
		}
		return ""
	}
	return ""
}

func (x *RouteResource) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *RouteResource) SetResource(v string) {
	x.xxx_hidden_Resource = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RouteResource) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RouteResource) SetRv(v string) {
	x.xxx_hidden_Rv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RouteResource) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RouteResource) HasResource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RouteResource) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RouteResource) HasRv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RouteResource) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RouteResource) ClearResource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Resource = nil
}

func (x *RouteResource) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *RouteResource) ClearRv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Rv = nil
}

func (x *RouteResource) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Raw = nil
}

type RouteResource_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// resource is the lowercase, plural parent resource name, such as dashboards.
	Resource *string
	// name is the parent resource name.
	Name *string
	// rv is the resource version. A change indicates that raw has changed.
	Rv *string
	// raw is the complete JSON-encoded parent resource.
	Raw []byte
}

func (b0 RouteResource_builder) Build() *RouteResource {
	m0 := &RouteResource{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Resource != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Resource = b.Resource
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.Rv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Rv = b.Rv
	}
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Raw = b.Raw
	}
	return m0
}

type HeaderValues struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values []string               `protobuf:"bytes,1,rep,name=values"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_plugin_v3_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *HeaderValues) SetValues(v []string) {
	x.xxx_hidden_Values = v
}

type HeaderValues_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values []string
}

func (b0 HeaderValues_builder) Build() *HeaderValues {
	m0 := &HeaderValues{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = b.Values
	return m0
}

// CallRouteRequest is the request for RouteService.CallRoute.
type CallRouteRequest struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Group       *string                  `protobuf:"bytes,1,opt,name=group"`
	xxx_hidden_Version     *string                  `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Namespace   *string                  `protobuf:"bytes,3,opt,name=namespace"`
	xxx_hidden_Parent      *RouteResource           `protobuf:"bytes,4,opt,name=parent"`
	xxx_hidden_Path        *string                  `protobuf:"bytes,5,opt,name=path"`
	xxx_hidden_Method      *string                  `protobuf:"bytes,6,opt,name=method"`
	xxx_hidden_Url         *string                  `protobuf:"bytes,7,opt,name=url"`
	xxx_hidden_Headers     map[string]*HeaderValues `protobuf:"bytes,8,rep,name=headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Body        []byte                   `protobuf:"bytes,9,opt,name=body"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CallRouteRequest) Reset() {
	*x = CallRouteRequest{}
	mi := &file_plugin_v3_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRouteRequest) ProtoMessage() {}

func (x *CallRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallRouteRequest) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetParent() *RouteResource {
	if x != nil {
		return x.xxx_hidden_Parent
	}
	return nil
}

func (x *CallRouteRequest) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetMethod() string {
	if x != nil {
		if x.xxx_hidden_Method != nil {
			return *x.xxx_hidden_Method
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *CallRouteRequest) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.xxx_hidden_Headers
	}
	return nil
}

func (x *CallRouteRequest) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *CallRouteRequest) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *CallRouteRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *CallRouteRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *CallRouteRequest) SetParent(v *RouteResource) {
	x.xxx_hidden_Parent = v
}

func (x *CallRouteRequest) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *CallRouteRequest) SetMethod(v string) {
	x.xxx_hidden_Method = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *CallRouteRequest) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *CallRouteRequest) SetHeaders(v map[string]*HeaderValues) {
	x.xxx_hidden_Headers = v
}

func (x *CallRouteRequest) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *CallRouteRequest) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallRouteRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CallRouteRequest) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CallRouteRequest) HasParent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parent != nil
}

func (x *CallRouteRequest) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CallRouteRequest) HasMethod() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CallRouteRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CallRouteRequest) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *CallRouteRequest) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Group = nil
}

func (x *CallRouteRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *CallRouteRequest) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Namespace = nil
}

func (x *CallRouteRequest) ClearParent() {
	x.xxx_hidden_Parent = nil
}

func (x *CallRouteRequest) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Path = nil
}

func (x *CallRouteRequest) ClearMethod() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Method = nil
}

func (x *CallRouteRequest) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Url = nil
}

func (x *CallRouteRequest) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Body = nil
}

type CallRouteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// group is the API group. For plugins, it is usually the plugin identifier.
	Group *string
	// version is the API version, such as v1 or v2beta1.
	Version *string
	// namespace identifies the tenant or resource namespace.
	Namespace *string
	// parent is set when the route targets a resource subresource.
	Parent *RouteResource
	// path is relative to the configured route location.
	Path *string
	// method is the HTTP method.
	Method *string
	// url is the request URL. The request's separate HTTP Host field is
	// intentionally not forwarded; host-based routing is not supported.
	Url *string
	// headers are the raw HTTP request headers. The HTTP Host is not included
	// because Go represents it separately from the header map.
	Headers map[string]*HeaderValues
	// body is the raw HTTP request body.
	Body []byte
}

func (b0 CallRouteRequest_builder) Build() *CallRouteRequest {
	m0 := &CallRouteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Version = b.Version
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Namespace = b.Namespace
	}
	x.xxx_hidden_Parent = b.Parent
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Path = b.Path
	}
	if b.Method != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_Method = b.Method
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_Url = b.Url
	}
	x.xxx_hidden_Headers = b.Headers
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

// CallRouteResponse is a streamed chunk of the response for RouteService.CallRoute.
// The code and headers will only be used for the first stream chunk.
type CallRouteResponse struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Code        int32                    `protobuf:"varint,1,opt,name=code"`
	xxx_hidden_Headers     map[string]*HeaderValues `protobuf:"bytes,2,rep,name=headers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Body        []byte                   `protobuf:"bytes,3,opt,name=body"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CallRouteResponse) Reset() {
	*x = CallRouteResponse{}
	mi := &file_plugin_v3_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRouteResponse) ProtoMessage() {}

func (x *CallRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v3_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CallRouteResponse) GetCode() int32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *CallRouteResponse) GetHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.xxx_hidden_Headers
	}
	return nil
}

func (x *CallRouteResponse) GetBody() []byte {
	if x != nil {
		return x.xxx_hidden_Body
	}
	return nil
}

func (x *CallRouteResponse) SetCode(v int32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CallRouteResponse) SetHeaders(v map[string]*HeaderValues) {
	x.xxx_hidden_Headers = v
}

func (x *CallRouteResponse) SetBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Body = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CallRouteResponse) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CallRouteResponse) HasBody() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CallRouteResponse) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Code = 0
}

func (x *CallRouteResponse) ClearBody() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Body = nil
}

type CallRouteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// code maps to raw HTTP status codes when passed over HTTP.
	// This is only respected in the first response payload.
	Code *int32
	// headers are the raw HTTP headers sent to the client.
	// This is only respected in the first response payload.
	Headers map[string]*HeaderValues
	// body contains the raw HTTP body bytes sent to the client.
	Body []byte
}

func (b0 CallRouteResponse_builder) Build() *CallRouteResponse {
	m0 := &CallRouteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Code = *b.Code
	}
	x.xxx_hidden_Headers = b.Headers
	if b.Body != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Body = b.Body
	}
	return m0
}

var File_plugin_v3_route_proto protoreflect.FileDescriptor

const file_plugin_v3_route_proto_rawDesc = "" +
	"\n" +
	"\x15plugin/v3/route.proto\x12\tplugin.v3\"a\n" +
	"\rRouteResource\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02rv\x18\x03 \x01(\tR\x02rv\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\fR\x03raw\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xfd\x02\n" +
	"\x10CallRouteRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x120\n" +
	"\x06parent\x18\x04 \x01(\v2\x18.plugin.v3.RouteResourceR\x06parent\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12B\n" +
	"\aheaders\x18\b \x03(\v2(.plugin.v3.CallRouteRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\t \x01(\fR\x04body\x1aS\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.plugin.v3.HeaderValuesR\x05value:\x028\x01\"\xd5\x01\n" +
	"\x11CallRouteResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12C\n" +
	"\aheaders\x18\x02 \x03(\v2).plugin.v3.CallRouteResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1aS\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.plugin.v3.HeaderValuesR\x05value:\x028\x012X\n" +
	"\fRouteService\x12H\n" +
	"\tCallRoute\x12\x1b.plugin.v3.CallRouteRequest\x1a\x1c.plugin.v3.CallRouteResponse0\x01B\xaa\x01\n" +
	"\rcom.plugin.v3B\n" +
	"RouteProtoP\x01ZHgithub.com/grafana/grafana-app-sdk/contracts/genproto/plugin/v3;pluginv3\xa2\x02\x03PXX\xaa\x02\tPlugin.V3\xca\x02\tPlugin\\V3\xe2\x02\x15Plugin\\V3\\GPBMetadata\xea\x02\n" +
	"Plugin::V3b\beditionsp\xe9\a"

var file_plugin_v3_route_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_v3_route_proto_goTypes = []any{
	(*RouteResource)(nil),     // 0: plugin.v3.RouteResource
	(*HeaderValues)(nil),      // 1: plugin.v3.HeaderValues
	(*CallRouteRequest)(nil),  // 2: plugin.v3.CallRouteRequest
	(*CallRouteResponse)(nil), // 3: plugin.v3.CallRouteResponse
	nil,                       // 4: plugin.v3.CallRouteRequest.HeadersEntry
	nil,                       // 5: plugin.v3.CallRouteResponse.HeadersEntry
}
var file_plugin_v3_route_proto_depIdxs = []int32{
	0, // 0: plugin.v3.CallRouteRequest.parent:type_name -> plugin.v3.RouteResource
	4, // 1: plugin.v3.CallRouteRequest.headers:type_name -> plugin.v3.CallRouteRequest.HeadersEntry
	5, // 2: plugin.v3.CallRouteResponse.headers:type_name -> plugin.v3.CallRouteResponse.HeadersEntry
	1, // 3: plugin.v3.CallRouteRequest.HeadersEntry.value:type_name -> plugin.v3.HeaderValues
	1, // 4: plugin.v3.CallRouteResponse.HeadersEntry.value:type_name -> plugin.v3.HeaderValues
	2, // 5: plugin.v3.RouteService.CallRoute:input_type -> plugin.v3.CallRouteRequest
	3, // 6: plugin.v3.RouteService.CallRoute:output_type -> plugin.v3.CallRouteResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_plugin_v3_route_proto_init() }
func file_plugin_v3_route_proto_init() {
	if File_plugin_v3_route_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v3_route_proto_rawDesc), len(file_plugin_v3_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v3_route_proto_goTypes,
		DependencyIndexes: file_plugin_v3_route_proto_depIdxs,
		MessageInfos:      file_plugin_v3_route_proto_msgTypes,
	}.Build()
	File_plugin_v3_route_proto = out.File
	file_plugin_v3_route_proto_goTypes = nil
	file_plugin_v3_route_proto_depIdxs = nil
}
