version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  groups:
    cue:
      patterns:
      - "*cue*"
      - "*thema*"
      - "*codejen*"
    all:
      exclude-patterns:
      - "*cue*"
      - "*thema*"
      - "*codejen*"
      patterns:
      - "*"
  labels:
  - "type/dependabot"
- package-ecosystem: gomod
  directory: "/plugin/"
  schedule:
    interval: daily
  groups:
    all:
      patterns:
      - "*"
# LTS branch
- package-ecosystem: gomod
  directory: "/"
  target-branch: "lts/v0.24"
  schedule:
    interval: daily
  groups:
    cue:
      patterns:
        - "*cue*"
        - "*thema*"
        - "*codejen*"
    all:
      exclude-patterns:
        - "*cue*"
        - "*thema*"
        - "*codejen*"
      patterns:
        - "*"
  labels:
    - "type/dependabot"
- package-ecosystem: gomod
  directory: "/plugin/"
  target-branch: "lts/v0.24"
  schedule:
    interval: daily
  groups:
    all:
      patterns:
        - "*"
      exclude-patterns:
        - "*grafana-app-sdk*" # Don't update the app-sdk version via dependabot for this branch