version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  groups:
    cue:
      patterns:
      - "*cue*"
      - "*thema*"
      - "*codejen*"
    all:
      exclude-patterns:
      - "*cue*"
      - "*thema*"
      - "*codejen*"
      patterns:
      - "*"
  labels:
  - "type/dependabot"
- package-ecosystem: gomod
  directory: "/plugin/"
  schedule:
    interval: daily
  groups:
    all:
      patterns:
      - "*"
