apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.MachineName}}-user
rules:
  - apiGroups:
      - {{.Group}}
    resources:
      - {{.PluralMachineName}}
      - {{.PluralMachineName}}/status
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.MachineName}}-lister
rules:
  - apiGroups:
      - {{.Group}}
    resources:
      - {{.PluralMachineName}}
    verbs:
      - get
      - list
      - watch