package cuekind

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/grafana/codejen"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/kube-openapi/pkg/spec3"
	"sigs.k8s.io/yaml"

	"github.com/grafana/grafana-app-sdk/app"
	"github.com/grafana/grafana-app-sdk/app/appmanifest/v1alpha2"
	"github.com/grafana/grafana-app-sdk/codegen/jennies"
)

func TestManifestGenerator_IntegrationOpenAPI(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)
	manifest, err := parser.ParseManifest("integrationManifest")
	require.NoError(t, err)
	assert.Equal(t, "integration.openapi.json", manifest.Versions()[0].Properties().ImportOpenAPIFile)

	for _, encoding := range []string{"json", "yaml"} {
		t.Run(encoding, func(t *testing.T) {
			generator := &jennies.ManifestGenerator{
				Encoder: jsonEncoder, FileExtension: encoding,
				IncludeSchemas: true, ManifestVersion: jennies.VersionV1Alpha2,
			}
			if encoding == "yaml" {
				generator.Encoder = yaml.Marshal
			}
			files, err := generator.Generate(manifest)
			require.NoError(t, err)
			require.Len(t, files, 1)
			// This snapshot belongs to the separate integration fixture, not the
			// manifests generated by configJson/configYaml in the CLI comparison job.
			// Only JSON is snapshotted; the YAML output is checked by decoding it below.
			if encoding == "json" {
				goldenPath := filepath.Join("testing", "golden", files[0].RelativePath+".txt")
				if os.Getenv("UPDATE_INTEGRATION_GOLDEN") == "1" {
					require.NoError(t, os.WriteFile(goldenPath, files[0].Data, 0644))
				}
				golden, err := os.ReadFile(goldenPath)
				require.NoError(t, err)
				assert.Equal(t, string(golden), string(files[0].Data))
			}
			var output struct {
				Spec v1alpha2.AppManifestSpec `json:"spec"`
			}
			require.NoError(t, yaml.Unmarshal(files[0].Data, &output))
			data, err := output.Spec.ToManifestData()
			require.NoError(t, err)
			require.Len(t, data.Versions, 1)
			version := data.Versions[0]
			// A new response type, not a new resource kind.
			require.Len(t, version.Kinds, 2)
			require.Contains(t, version.Routes.Schemas, "Report")
			report := version.Routes.Schemas["Report"]
			assert.Equal(t, []string{"message", "count"}, report.Required)
			assert.Contains(t, report.Properties["message"].Type, "string")
			assert.Equal(t, "int64", report.Properties["count"].Format)

			cluster := version.Routes.Cluster["/foo-from-openapi-file"]
			require.NotNil(t, cluster.Get)
			assert.Equal(t, "getFooFromOpenAPI", cluster.Get.OperationId)
			namespaced := version.Routes.Namespaced["/bar-from-openapi-file"]
			require.NotNil(t, namespaced.Get)
			assert.Equal(t, "getNamespacedReport", namespaced.Get.OperationId)
			assert.Contains(t, version.Routes.Cluster, "/bar-from-routes-cluster-cue")
			assert.Contains(t, version.Routes.Namespaced, "/foo-from-routes-namespaced-cue")

			foo := version.Kinds[0]
			require.Equal(t, "Foo", foo.Kind)
			assert.Contains(t, foo.Routes, "/sub-kind-from-cue")
			require.NotNil(t, version.OpenAPI.Paths)
			// The output openapi section is the union of all custom route sources,
			// not just the inline openapi block in integration.cue. All paths here
			// are relative to the version root, including namespace and kind prefixes.
			require.Len(t, version.OpenAPI.Paths, 6)
			for _, path := range []string{
				// Legacy version-level CUE routes.
				"/bar-from-routes-cluster-cue",
				"/namespaces/{namespace}/foo-from-routes-namespaced-cue",
				// Kind-level CUE subresource route.
				"/namespaces/{namespace}/foos/{name}/sub-kind-from-cue",
				// Paths imported from integration.openapi.json.
				"/foo-from-openapi-file",
				"/namespaces/{namespace}/bar-from-openapi-file",
				// Inline OpenAPI in integration.cue.
				"/foo-from-inline-openapi-cue",
			} {
				assert.Contains(t, version.OpenAPI.Paths, path)
			}
			assert.Equal(t, "getFooFromCue", version.OpenAPI.Paths["/foo-from-inline-openapi-cue"].Get.OperationId)
			require.False(t, version.OpenAPI.Components.IsZero())
			assert.Contains(t, version.OpenAPI.Components.Schemas, "Report")
			raw, err := json.Marshal(version.OpenAPI)
			require.NoError(t, err)
			var document any
			require.NoError(t, json.Unmarshal(raw, &document))
			var checkRefs func(any)
			checkRefs = func(value any) {
				switch value := value.(type) {
				case map[string]any:
					if ref, ok := value["$ref"].(string); ok {
						require.True(t, strings.HasPrefix(ref, "#/components/schemas/"), ref)
						assert.Contains(t, version.OpenAPI.Components.Schemas, strings.TrimPrefix(ref, "#/components/schemas/"))
					}
					for _, child := range value {
						checkRefs(child)
					}
				case []any:
					for _, child := range value {
						checkRefs(child)
					}
				}
			}
			checkRefs(document)
			details := version.OpenAPI.Paths["/namespaces/{namespace}/foos/{name}/sub-kind-from-cue"]
			require.Len(t, details.Parameters, 2)
			assert.Equal(t, "namespace", details.Parameters[0].Name)
			assert.Equal(t, "name", details.Parameters[1].Name)

			assert.Empty(t, cluster.Get.Parameters)
			for _, check := range []struct {
				parameters []*spec3.Parameter
				names      []string
			}{
				{namespaced.Get.Parameters, []string{"namespace"}},
			} {
				require.Len(t, check.parameters, len(check.names))
				for idx, parameter := range check.parameters {
					assert.Equal(t, check.names[idx], parameter.Name)
					assert.Equal(t, "path", parameter.In)
					assert.True(t, parameter.Required)
					require.NotNil(t, parameter.Schema)
					assert.Contains(t, parameter.Schema.Type, "string")
				}
			}
			for _, route := range []spec3.PathProps{cluster, namespaced} {
				response := route.Get.Responses.StatusCodeResponses[200]
				assert.Equal(t, "#/components/schemas/Report", response.Content["application/json"].Schema.Ref.String())
			}
		})
	}

	files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
		Package: "manifestdata", IncludeSchemas: true, ProjectRepo: "codegen-tests",
		GoGenPath: "pkg/generated", ManifestGoFilePath: "manifestdata",
		GroupKinds: true, SkipImportsProcess: true,
	}).Generate(manifest)
	require.NoError(t, err)
	for _, file := range files {
		if strings.HasSuffix(file.RelativePath, "_manifest.go") {
			source := string(file.Data)
			assert.Contains(t, source, "getFooFromCue")
			assert.Contains(t, source, "getFooFromOpenAPI")
			assert.Contains(t, source, "GetDetailsResponse{}")
			assert.NotContains(t, source, "GetFooReportResponse{}")
			assert.NotContains(t, source, "GetClusterReportResponse{}")
			assert.NotContains(t, source, "GetNamespacedReportResponse{}")
			continue
		}
		assert.NotContains(t, strings.ToLower(file.RelativePath), "report")
		assert.NotContains(t, string(file.Data), "getFooReport")
	}
}

const (
	ReferenceOutputDirectory = "../testing/golden_generated"
)

func TestCRDGenerator(t *testing.T) {
	// Ideally, we test only that this outputs the right jennies,
	// but right now we just test the whole pipeline from thema -> written files

	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)
	kinds, err := parser.ManifestParser().Parse("customManifest", "testManifest")
	require.NoError(t, err)

	t.Run("JSON", func(t *testing.T) {
		files, err := CRDGenerator(jsonEncoder, "json").Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		assert.Len(t, files, 3)
		// Check content against the golden files
		compareToGolden(t, files, "crd")
	})

	t.Run("YAML", func(t *testing.T) {
		files, err := CRDGenerator(yaml.Marshal, "yaml").Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		assert.Len(t, files, 3)
		// Check content against the golden files
		compareToGolden(t, files, "crd")
	})
}

func TestResourceGenerator(t *testing.T) {
	// Ideally, we test only that this outputs the right jennies,
	// but right now we just test the whole pipeline from thema -> written files

	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)
	kinds, err := parser.ManifestParser().Parse("customManifest")
	require.NoError(t, err)
	sameGroupKinds, err := parser.ManifestParser().Parse("testManifest")
	require.NoError(t, err)

	t.Run("group by kind", func(t *testing.T) {
		files, err := ResourceGenerator("codegen-tests", "pkg/generated", false).Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		// 12 (7 -> object, spec, status, schema, codec, constants) * 2 versions
		assert.Len(t, files, 12, "should be 12 files generated, got %d", len(files))
		// Check content against the golden files
		compareToGolden(t, files, "go/groupbykind")
	})

	t.Run("group by group", func(t *testing.T) {
		files, err := ResourceGenerator("codegen-tests", "pkg/generated", true).Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		// 12 (7 -> object, spec, status, schema, codec, constants) * 2 versions
		assert.Len(t, files, 12, "should be 12 files generated, got %d", len(files))
		// Check content against the golden files
		compareToGolden(t, files, "go/groupbygroup")
	})

	t.Run("group by group, multiple kinds", func(t *testing.T) {
		files, err := ResourceGenerator("codegen-tests", "pkg/generated", true).Generate(sameGroupKinds...)
		require.NoError(t, err)
		// Check number of files generated
		// Prior: 23 for v1–v3; +6 for v4 TestKind (object, spec, status, schema, codec, constants)
		assert.Len(t, files, 29, "should be 29 files generated, got %d", len(files))
		// Check content against the golden files
		compareToGolden(t, files, "go/groupbygroup")
	})
}

func TestTypeScriptResourceGenerator(t *testing.T) {
	// Ideally, we test only that this outputs the right jennies,
	// but right now we just test the whole pipeline from thema -> written files

	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)

	t.Run("versioned", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("customManifest")
		require.NoError(t, err)
		files, err := TypeScriptResourceGenerator().Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		assert.Len(t, files, 8)
		// Check content against the golden files
		compareToGolden(t, files, "typescript/versioned")
	})
}

func TestManifestGenerator(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)

	t.Run("resource", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("testManifest")
		require.NoError(t, err)
		files, err := ManifestGenerator(ManifestGeneratorConfig{
			Extension:      "json",
			IncludeSchemas: true,
			Version:        jennies.VersionV1Alpha2,
		}).Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		// 5 -> object, spec, metadata, status, schema
		assert.Len(t, files, 1)
		// Check content against the golden files
		compareToGolden(t, files, "manifest")
	})

	t.Run("filename override", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("testManifest")
		require.NoError(t, err)
		files, err := ManifestGenerator(ManifestGeneratorConfig{
			Extension:      "json",
			FileName:       "my-manifest.json",
			IncludeSchemas: true,
			Version:        jennies.VersionV1Alpha1,
		}).Generate(kinds...)
		require.NoError(t, err)
		require.Len(t, files, 1)
		assert.Equal(t, "my-manifest.json", files[0].RelativePath)
	})

	t.Run("empty filename uses the default", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("testManifest")
		require.NoError(t, err)
		files, err := ManifestGenerator(ManifestGeneratorConfig{
			Extension:      "yaml",
			IncludeSchemas: true,
			Version:        jennies.VersionV1Alpha1,
		}).Generate(kinds...)
		require.NoError(t, err)
		require.Len(t, files, 1)
		assert.Equal(t, "test-app-manifest.yaml", files[0].RelativePath)
	})
}

func TestManifestGenerator_EmbeddingSettings(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)
	manifests, err := parser.ManifestParser().Parse("testManifest")
	require.NoError(t, err)

	for _, extension := range []string{"json", "yaml"} {
		t.Run(extension, func(t *testing.T) {
			files, err := ManifestGenerator(ManifestGeneratorConfig{
				Extension:      extension,
				IncludeSchemas: true,
				Version:        jennies.VersionV1Alpha2,
			}).Generate(manifests...)
			require.NoError(t, err)
			require.Len(t, files, 1)

			var manifest struct {
				APIVersion string                   `json:"apiVersion"`
				Spec       v1alpha2.AppManifestSpec `json:"spec"`
			}
			require.NoError(t, yaml.Unmarshal(files[0].Data, &manifest))
			assert.Equal(t, v1alpha2.GroupVersion.String(), manifest.APIVersion)
			data, err := manifest.Spec.ToManifestData()
			require.NoError(t, err)
			assert.Equal(t, map[string]app.ManifestResourceEmbed{"testkinds": {ReembedVersion: 1}}, data.Embed)
			assert.Equal(t, 1, strings.Count(string(files[0].Data), "reembedVersion"))

			foundEmbeddedKind := false
			for _, version := range data.Versions {
				for _, kind := range version.Kinds {
					if kind.Kind != "TestKind" {
						continue
					}
					if version.Name != "v2" {
						if version.Name == "v1" {
							assert.Equal(t, &app.ManifestVersionKindEmbed{
								Fields: []app.ManifestVersionKindEmbedField{{Name: "details", Path: "spec.stringField"}},
							}, kind.Embed)
						} else {
							assert.Nil(t, kind.Embed)
						}
						assert.False(t, kind.HasHybridEndpoint())
						assert.False(t, kind.InGlobalSearchIndex())
						continue
					}

					foundEmbeddedKind = true
					require.NotNil(t, kind.Embed)
					assert.Equal(t, &app.ManifestVersionKindEmbed{
						Fields: []app.ManifestVersionKindEmbedField{
							{Name: "details", Path: "spec.unionNull.str"},
						},
					}, kind.Embed)
					assert.True(t, kind.HasHybridEndpoint())
					assert.True(t, kind.InGlobalSearchIndex())
					require.Len(t, kind.SearchFields, 2)
					assert.Equal(t, "stringField", kind.SearchFields[0].Name)
					assert.Equal(t, "intField", kind.SearchFields[1].Name)
				}
			}
			require.True(t, foundEmbeddedKind)
		})
	}
}

func TestManifestGoGenerator(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)

	t.Run("group by group", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("testManifest")
		require.NoError(t, err)
		files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
			Package:            "manifestdata",
			IncludeSchemas:     true,
			ProjectRepo:        "codegen-tests",
			GoGenPath:          "pkg/generated",
			ManifestGoFilePath: "manifestdata",
			GroupKinds:         true,
		}).Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		// 18 -> prior 15 (manifest, reconcile/search/foobar routes + v1–v3 clients + v3 route client) + v4 resource client (1)
		// + empty response route body and object (2)
		require.Len(t, files, 18, "should be 18 files generated, got %d", len(files))
		// Check content against the golden files
		for _, file := range files {
			compareToGolden(t, codejen.Files{file}, "go/groupbygroup")
		}
	})

	t.Run("group by kind", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("customManifest")
		require.NoError(t, err)
		files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
			Package:            "manifestdata",
			IncludeSchemas:     true,
			ProjectRepo:        "codegen-tests",
			GoGenPath:          "pkg/generated",
			ManifestGoFilePath: "manifestdata",
		}).Generate(kinds...)
		require.NoError(t, err)
		// Check number of files generated
		// 3 -> manifest, client v0_0, client v1_0
		assert.Len(t, files, 3)
		// Check content against the golden files
		for _, file := range files {
			compareToGolden(t, codejen.Files{file}, "go/groupbykind")
		}
	})
}

func TestManifestGoGenerator_Deterministic(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)

	t.Run("group by group", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("testManifest")
		require.NoError(t, err)

		var reference codejen.Files
		for i := range 5 {
			files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
				Package:            "manifestdata",
				IncludeSchemas:     true,
				ProjectRepo:        "codegen-tests",
				GoGenPath:          "pkg/generated",
				ManifestGoFilePath: "manifestdata",
				GroupKinds:         true,
				SkipImportsProcess: true,
			}).Generate(kinds...)
			require.NoError(t, err)
			if i == 0 {
				reference = files
				continue
			}
			for j, f := range files {
				assert.Equal(t, string(reference[j].Data), string(f.Data),
					"non-deterministic output on iteration %d for file %s", i, f.RelativePath)
			}
		}
	})

	t.Run("group by kind", func(t *testing.T) {
		kinds, err := parser.ManifestParser().Parse("customManifest")
		require.NoError(t, err)

		var reference codejen.Files
		for i := range 5 {
			files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
				Package:            "manifestdata",
				IncludeSchemas:     true,
				ProjectRepo:        "codegen-tests",
				GoGenPath:          "pkg/generated",
				ManifestGoFilePath: "manifestdata",
				SkipImportsProcess: true,
			}).Generate(kinds...)
			require.NoError(t, err)
			if i == 0 {
				reference = files
				continue
			}
			for j, f := range files {
				assert.Equal(t, string(reference[j].Data), string(f.Data),
					"non-deterministic output on iteration %d for file %s", i, f.RelativePath)
			}
		}
	})
}

func TestManifestGoGenerator_RolesAreSorted(t *testing.T) {
	parser, err := NewParser(testingCue(t), true)
	require.NoError(t, err)

	kinds, err := parser.ManifestParser().Parse("testManifest")
	require.NoError(t, err)
	files, err := ManifestGoGenerator(ManifestGoGeneratorConfig{
		Package:            "manifestdata",
		IncludeSchemas:     true,
		ProjectRepo:        "codegen-tests",
		GoGenPath:          "pkg/generated",
		ManifestGoFilePath: "manifestdata",
		GroupKinds:         true,
	}).Generate(kinds...)
	require.NoError(t, err)
	require.NotEmpty(t, files)

	manifest := string(files[0].Data)
	idx := strings.Index(manifest, "Roles: map[string]app.ManifestRole{")
	if idx == -1 {
		t.Skip("no Roles map found in generated manifest")
	}
	rolesSection := manifest[idx:]

	// Find all quoted role keys in order of appearance
	var keys []string
	for line := range strings.SplitSeq(rolesSection, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, `"`) && strings.Contains(trimmed, `": {`) {
			key := strings.SplitN(trimmed, `"`, 3)[1]
			keys = append(keys, key)
		}
		if trimmed == "}," && len(keys) > 0 {
			break
		}
	}
	require.NotEmpty(t, keys, "should find role keys in generated manifest")
	assert.IsNonDecreasing(t, keys, "role keys should appear in sorted order")
}

func compareToGolden(t *testing.T, files codejen.Files, pathPrefix string) {
	t.Helper()
	for _, f := range files {
		goldenPath := filepath.Join(ReferenceOutputDirectory, pathPrefix, f.RelativePath+".txt")
		// Check if there's a golden generated file to compare against
		file, err := os.ReadFile(goldenPath)
		require.NoError(t, err)
		// Compare the contents of the file to the generated contents
		// Use strings for easier-to-read diff in the event of a mismatch
		assert.Equal(t, string(file), string(f.Data))
	}
}

func testingCue(t *testing.T) *Cue {
	root, err := LoadCue(os.DirFS("./testing"))
	require.NoError(t, err)
	return root
}
