// EXPERIMENTAL: Plugin protocol v3 is a work in progress.
// The APIs and wire format may change or be removed without notice.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: watch/v1/watch.proto

package watchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupVersion represents the API group and version of a resource.
type Event struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group       *string                `protobuf:"bytes,1,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_watch_v1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_watch_v1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *Event) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Event) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Event) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Event) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Event) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Event) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Group = nil
}

func (x *Event) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// group is the API group.
	Group *string
	// version is the API version, such as v1 or v2beta1.
	Version *string
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = b.Version
	}
	return m0
}

var File_watch_v1_watch_proto protoreflect.FileDescriptor

const file_watch_v1_watch_proto_rawDesc = "" +
	"\n" +
	"\x14watch/v1/watch.proto\x12\bwatch.v1\"7\n" +
	"\x05Event\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversionB\xa3\x01\n" +
	"\fcom.watch.v1B\n" +
	"WatchProtoP\x01ZFgithub.com/grafana/grafana-app-sdk/contracts/genproto/watch/v1;watchv1\xa2\x02\x03WXX\xaa\x02\bWatch.V1\xca\x02\bWatch\\V1\xe2\x02\x14Watch\\V1\\GPBMetadata\xea\x02\tWatch::V1b\beditionsp\xe9\a"

var file_watch_v1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_watch_v1_watch_proto_goTypes = []any{
	(*Event)(nil), // 0: watch.v1.Event
}
var file_watch_v1_watch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_watch_v1_watch_proto_init() }
func file_watch_v1_watch_proto_init() {
	if File_watch_v1_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watch_v1_watch_proto_rawDesc), len(file_watch_v1_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_watch_v1_watch_proto_goTypes,
		DependencyIndexes: file_watch_v1_watch_proto_depIdxs,
		MessageInfos:      file_watch_v1_watch_proto_msgTypes,
	}.Build()
	File_watch_v1_watch_proto = out.File
	file_watch_v1_watch_proto_goTypes = nil
	file_watch_v1_watch_proto_depIdxs = nil
}
