//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	kindSchema = resource.NewSimpleSchema("core.grafana.internal", "v1", &ExternalName{}, &ExternalNameList{}, resource.WithKind("ExternalName"),
		resource.WithPlural("externalnames"), resource.WithScope(resource.ClusterScope))
	kind = resource.Kind{
		Schema: kindSchema,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &JSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func Kind() resource.Kind {
	return kind
}

// Schema returns a resource.SimpleSchema representation of ExternalName
func Schema() *resource.SimpleSchema {
	return kindSchema
}

// Interface compliance checks
var _ resource.Schema = kindSchema
