apiVersion: v1
kind: Namespace
metadata:
  name: app-sdk-sharding
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: app-sdk-sharding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: memcached:1.6-alpine
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: app-sdk-sharding
spec:
  selector:
    app: memcached
  ports:
    - port: 11211
      targetPort: 11211
