//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha2

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaAppManifest = resource.NewSimpleSchema("apps.grafana.com", "v1alpha2", &AppManifest{}, &AppManifestList{}, resource.WithKind("AppManifest"),
		resource.WithPlural("appmanifests"), resource.WithScope(resource.ClusterScope))
	kindAppManifest = resource.Kind{
		Schema: schemaAppManifest,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &AppManifestJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func AppManifestKind() resource.Kind {
	return kindAppManifest
}

// Schema returns a resource.SimpleSchema representation of AppManifest
func AppManifestSchema() *resource.SimpleSchema {
	return schemaAppManifest
}

// Interface compliance checks
var _ resource.Schema = kindAppManifest
