// Code generated - EDITING IS FUTILE. DO NOT EDIT.

package v1alpha1

// +k8s:openapi-gen=true
type TestKindPrefixFoo struct {
	Foo string            `json:"foo"`
	Bar TestKindPrefixBar `json:"bar"`
}

// NewTestKindPrefixFoo creates a new TestKindPrefixFoo object.
func NewTestKindPrefixFoo() *TestKindPrefixFoo {
	return &TestKindPrefixFoo{
		Foo: "foo",
		Bar: *NewTestKindPrefixBar(),
	}
}

// OpenAPIModelName returns the OpenAPI model name for TestKindPrefixFoo.
func (TestKindPrefixFoo) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.examples.apiserver.apis.example.v1alpha1.TestKindPrefixFoo"
}

// +k8s:openapi-gen=true
type TestKindPrefixBar struct {
	Value string            `json:"value"`
	Baz   TestKindPrefixBaz `json:"baz"`
}

// NewTestKindPrefixBar creates a new TestKindPrefixBar object.
func NewTestKindPrefixBar() *TestKindPrefixBar {
	return &TestKindPrefixBar{
		Value: "bar",
		Baz:   *NewTestKindPrefixBaz(),
	}
}

// OpenAPIModelName returns the OpenAPI model name for TestKindPrefixBar.
func (TestKindPrefixBar) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.examples.apiserver.apis.example.v1alpha1.TestKindPrefixBar"
}

// +k8s:openapi-gen=true
type TestKindPrefixBaz struct {
	Value int64 `json:"value"`
}

// NewTestKindPrefixBaz creates a new TestKindPrefixBaz object.
func NewTestKindPrefixBaz() *TestKindPrefixBaz {
	return &TestKindPrefixBaz{
		Value: 10,
	}
}

// OpenAPIModelName returns the OpenAPI model name for TestKindPrefixBaz.
func (TestKindPrefixBaz) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.examples.apiserver.apis.example.v1alpha1.TestKindPrefixBaz"
}

// +k8s:openapi-gen=true
type TestKindOther struct {
	// The generated go type here would normally conflict with Foo generated by spec, but the prefix should make that not happen
	Foo TestKindPrefixFoo `json:"foo"`
	Bar string            `json:"bar"`
}

// NewTestKindOther creates a new TestKindOther object.
func NewTestKindOther() *TestKindOther {
	return &TestKindOther{
		Foo: *NewTestKindPrefixFoo(),
	}
}

// OpenAPIModelName returns the OpenAPI model name for TestKindOther.
func (TestKindOther) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.examples.apiserver.apis.example.v1alpha1.TestKindOther"
}
