//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha1

import (
    "github.com/grafana/grafana-app-sdk/resource"
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
    "k8s.io/apimachinery/pkg/runtime"
)

type GetfooWrapper struct {
    metav1.TypeMeta `json:",inline"`
    Object Getfoo `json:",inline"`
}

func (g *GetfooWrapper) DeepCopyObject() runtime.Object {
	return g.DeepCopy()
}

func (g *GetfooWrapper) DeepCopy() *GetfooWrapper {
	cpy := &GetfooWrapper{}
	g.DeepCopyInto(cpy)
	return cpy
}

func (g *GetfooWrapper) DeepCopyInto(dst *GetfooWrapper) {
	resource.CopyObjectInto(dst, g)
}

// Interface compliance compile-time check
var _ runtime.Object = &GetfooWrapper{}