# This spec serves to illustrate the custom resource defined in-code. It does not need to be applied to the cluster for the basic operator to work
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: basiccustomresources.example.grafana.com
spec:
  group: example.grafana.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                numField:
                  type: integer
                  minimum: 1
                stringField:
                  type: string
  names:
    kind: BasicCustomResource
    plural: basiccustomresources
  scope: Namespaced