// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/plugin/v3/admission.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateAdmissionRequest contains information from a Kubernetes admission
// request and the decoded object(s).
type AdmissionReviewRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Operation      Operation              `protobuf:"varint,1,opt,name=operation,enum=grafana.plugin.v3.Operation"`
	xxx_hidden_Kind           *GroupVersionKind      `protobuf:"bytes,2,opt,name=kind"`
	xxx_hidden_ObjectBytes    []byte                 `protobuf:"bytes,3,opt,name=object_bytes,json=objectBytes"`
	xxx_hidden_OldObjectBytes []byte                 `protobuf:"bytes,4,opt,name=old_object_bytes,json=oldObjectBytes"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AdmissionReviewRequest) Reset() {
	*x = AdmissionReviewRequest{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionReviewRequest) ProtoMessage() {}

func (x *AdmissionReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdmissionReviewRequest) GetOperation() Operation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Operation
		}
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *AdmissionReviewRequest) GetKind() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return nil
}

func (x *AdmissionReviewRequest) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *AdmissionReviewRequest) GetOldObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_OldObjectBytes
	}
	return nil
}

func (x *AdmissionReviewRequest) SetOperation(v Operation) {
	x.xxx_hidden_Operation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AdmissionReviewRequest) SetKind(v *GroupVersionKind) {
	x.xxx_hidden_Kind = v
}

func (x *AdmissionReviewRequest) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *AdmissionReviewRequest) SetOldObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OldObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *AdmissionReviewRequest) HasOperation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdmissionReviewRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *AdmissionReviewRequest) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AdmissionReviewRequest) HasOldObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AdmissionReviewRequest) ClearOperation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Operation = Operation_OPERATION_UNSPECIFIED
}

func (x *AdmissionReviewRequest) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *AdmissionReviewRequest) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ObjectBytes = nil
}

func (x *AdmissionReviewRequest) ClearOldObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OldObjectBytes = nil
}

type AdmissionReviewRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation is the requested operation.
	Operation *Operation
	// kind is the object kind.
	Kind *GroupVersionKind
	// object_bytes is the object in the request, including the full metadata envelope.
	ObjectBytes []byte
	// old_object_bytes is the object as it currently exists in storage,
	// including the full metadata envelope.
	OldObjectBytes []byte
}

func (b0 AdmissionReviewRequest_builder) Build() *AdmissionReviewRequest {
	m0 := &AdmissionReviewRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Operation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Operation = *b.Operation
	}
	x.xxx_hidden_Kind = b.Kind
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	if b.OldObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OldObjectBytes = b.OldObjectBytes
	}
	return m0
}

// ValidateAdmissionResponse reports whether an object may be admitted.
type AdmissionReviewResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Allowed     bool                   `protobuf:"varint,1,opt,name=allowed"`
	xxx_hidden_Result      *StatusResult          `protobuf:"bytes,2,opt,name=result"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,3,rep,name=warnings"`
	xxx_hidden_ObjectBytes []byte                 `protobuf:"bytes,4,opt,name=object_bytes,json=objectBytes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdmissionReviewResponse) Reset() {
	*x = AdmissionReviewResponse{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionReviewResponse) ProtoMessage() {}

func (x *AdmissionReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdmissionReviewResponse) GetAllowed() bool {
	if x != nil {
		return x.xxx_hidden_Allowed
	}
	return false
}

func (x *AdmissionReviewResponse) GetResult() *StatusResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *AdmissionReviewResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *AdmissionReviewResponse) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *AdmissionReviewResponse) SetAllowed(v bool) {
	x.xxx_hidden_Allowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *AdmissionReviewResponse) SetResult(v *StatusResult) {
	x.xxx_hidden_Result = v
}

func (x *AdmissionReviewResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *AdmissionReviewResponse) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *AdmissionReviewResponse) HasAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdmissionReviewResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *AdmissionReviewResponse) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *AdmissionReviewResponse) ClearAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Allowed = false
}

func (x *AdmissionReviewResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *AdmissionReviewResponse) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ObjectBytes = nil
}

type AdmissionReviewResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// allowed indicates whether or not the admission request was permitted.
	Allowed *bool
	// result contains extra detail about why an admission request was denied.
	// It is not consulted in any way when allowed is true.
	Result *StatusResult
	// warnings is a list of warning messages to return to the requesting client.
	// Limit warnings to 120 characters if possible. Warnings over 256 characters
	// and large numbers of warnings may be truncated.
	Warnings []string
	// object_bytes are included when the object should change
	ObjectBytes []byte
}

func (b0 AdmissionReviewResponse_builder) Build() *AdmissionReviewResponse {
	m0 := &AdmissionReviewResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Allowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Allowed = *b.Allowed
	}
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Warnings = b.Warnings
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	return m0
}

var File_grafana_plugin_v3_admission_proto protoreflect.FileDescriptor

const file_grafana_plugin_v3_admission_proto_rawDesc = "" +
	"\n" +
	"!grafana/plugin/v3/admission.proto\x12\x11grafana.plugin.v3\x1a\x1egrafana/plugin/v3/common.proto\"\xda\x01\n" +
	"\x16AdmissionReviewRequest\x12:\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1c.grafana.plugin.v3.OperationR\toperation\x127\n" +
	"\x04kind\x18\x02 \x01(\v2#.grafana.plugin.v3.GroupVersionKindR\x04kind\x12!\n" +
	"\fobject_bytes\x18\x03 \x01(\fR\vobjectBytes\x12(\n" +
	"\x10old_object_bytes\x18\x04 \x01(\fR\x0eoldObjectBytes\"\xab\x01\n" +
	"\x17AdmissionReviewResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.grafana.plugin.v3.StatusResultR\x06result\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x12!\n" +
	"\fobject_bytes\x18\x04 \x01(\fR\vobjectBytes2|\n" +
	"\x10AdmissionService\x12h\n" +
	"\x0fAdmissionReview\x12).grafana.plugin.v3.AdmissionReviewRequest\x1a*.grafana.plugin.v3.AdmissionReviewResponseB\xe1\x01\n" +
	"\x15com.grafana.plugin.v3B\x0eAdmissionProtoP\x01ZRgithub.com/grafana/grafana-app-sdk/plugin-next/genproto/grafana/plugin/v3;pluginv3\xa2\x02\x03GPX\xaa\x02\x11Grafana.Plugin.V3\xca\x02\x11Grafana\\Plugin\\V3\xe2\x02\x1dGrafana\\Plugin\\V3\\GPBMetadata\xea\x02\x13Grafana::Plugin::V3b\beditionsp\xe9\a"

var file_grafana_plugin_v3_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grafana_plugin_v3_admission_proto_goTypes = []any{
	(*AdmissionReviewRequest)(nil),  // 0: grafana.plugin.v3.AdmissionReviewRequest
	(*AdmissionReviewResponse)(nil), // 1: grafana.plugin.v3.AdmissionReviewResponse
	(Operation)(0),                  // 2: grafana.plugin.v3.Operation
	(*GroupVersionKind)(nil),        // 3: grafana.plugin.v3.GroupVersionKind
	(*StatusResult)(nil),            // 4: grafana.plugin.v3.StatusResult
}
var file_grafana_plugin_v3_admission_proto_depIdxs = []int32{
	2, // 0: grafana.plugin.v3.AdmissionReviewRequest.operation:type_name -> grafana.plugin.v3.Operation
	3, // 1: grafana.plugin.v3.AdmissionReviewRequest.kind:type_name -> grafana.plugin.v3.GroupVersionKind
	4, // 2: grafana.plugin.v3.AdmissionReviewResponse.result:type_name -> grafana.plugin.v3.StatusResult
	0, // 3: grafana.plugin.v3.AdmissionService.AdmissionReview:input_type -> grafana.plugin.v3.AdmissionReviewRequest
	1, // 4: grafana.plugin.v3.AdmissionService.AdmissionReview:output_type -> grafana.plugin.v3.AdmissionReviewResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grafana_plugin_v3_admission_proto_init() }
func file_grafana_plugin_v3_admission_proto_init() {
	if File_grafana_plugin_v3_admission_proto != nil {
		return
	}
	file_grafana_plugin_v3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_plugin_v3_admission_proto_rawDesc), len(file_grafana_plugin_v3_admission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grafana_plugin_v3_admission_proto_goTypes,
		DependencyIndexes: file_grafana_plugin_v3_admission_proto_depIdxs,
		MessageInfos:      file_grafana_plugin_v3_admission_proto_msgTypes,
	}.Build()
	File_grafana_plugin_v3_admission_proto = out.File
	file_grafana_plugin_v3_admission_proto_goTypes = nil
	file_grafana_plugin_v3_admission_proto_depIdxs = nil
}
