// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grafana/plugin/v3/mutate.proto

package pluginv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MutateService_MutateObject_FullMethodName = "/grafana.plugin.v3.MutateService/MutateObject"
)

// MutateServiceClient is the client API for MutateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/admission/types.go#L41
type MutateServiceClient interface {
	// MutateObject returns a modified copy of the request that can be saved,
	// or a descriptive error.
	MutateObject(ctx context.Context, in *MutateObjectRequest, opts ...grpc.CallOption) (*MutateObjectResponse, error)
}

type mutateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutateServiceClient(cc grpc.ClientConnInterface) MutateServiceClient {
	return &mutateServiceClient{cc}
}

func (c *mutateServiceClient) MutateObject(ctx context.Context, in *MutateObjectRequest, opts ...grpc.CallOption) (*MutateObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateObjectResponse)
	err := c.cc.Invoke(ctx, MutateService_MutateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutateServiceServer is the server API for MutateService service.
// All implementations should embed UnimplementedMutateServiceServer
// for forward compatibility.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/admission/types.go#L41
type MutateServiceServer interface {
	// MutateObject returns a modified copy of the request that can be saved,
	// or a descriptive error.
	MutateObject(context.Context, *MutateObjectRequest) (*MutateObjectResponse, error)
}

// UnimplementedMutateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutateServiceServer struct{}

func (UnimplementedMutateServiceServer) MutateObject(context.Context, *MutateObjectRequest) (*MutateObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MutateObject not implemented")
}
func (UnimplementedMutateServiceServer) testEmbeddedByValue() {}

// UnsafeMutateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutateServiceServer will
// result in compilation errors.
type UnsafeMutateServiceServer interface {
	mustEmbedUnimplementedMutateServiceServer()
}

func RegisterMutateServiceServer(s grpc.ServiceRegistrar, srv MutateServiceServer) {
	// If the following call panics, it indicates UnimplementedMutateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MutateService_ServiceDesc, srv)
}

func _MutateService_MutateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutateServiceServer).MutateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutateService_MutateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutateServiceServer).MutateObject(ctx, req.(*MutateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MutateService_ServiceDesc is the grpc.ServiceDesc for MutateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.v3.MutateService",
	HandlerType: (*MutateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateObject",
			Handler:    _MutateService_MutateObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grafana/plugin/v3/mutate.proto",
}
