// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/plugin/v3/mutate.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MutateAdmissionRequest contains information from a Kubernetes admission
// request and the decoded object(s).
type MutateObjectRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Operation      Operation              `protobuf:"varint,1,opt,name=operation,enum=grafana.plugin.v3.Operation"`
	xxx_hidden_Kind           *GroupVersionKind      `protobuf:"bytes,2,opt,name=kind"`
	xxx_hidden_ObjectBytes    []byte                 `protobuf:"bytes,3,opt,name=object_bytes,json=objectBytes"`
	xxx_hidden_OldObjectBytes []byte                 `protobuf:"bytes,4,opt,name=old_object_bytes,json=oldObjectBytes"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MutateObjectRequest) Reset() {
	*x = MutateObjectRequest{}
	mi := &file_grafana_plugin_v3_mutate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateObjectRequest) ProtoMessage() {}

func (x *MutateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_mutate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MutateObjectRequest) GetOperation() Operation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Operation
		}
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *MutateObjectRequest) GetKind() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return nil
}

func (x *MutateObjectRequest) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *MutateObjectRequest) GetOldObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_OldObjectBytes
	}
	return nil
}

func (x *MutateObjectRequest) SetOperation(v Operation) {
	x.xxx_hidden_Operation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MutateObjectRequest) SetKind(v *GroupVersionKind) {
	x.xxx_hidden_Kind = v
}

func (x *MutateObjectRequest) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *MutateObjectRequest) SetOldObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OldObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *MutateObjectRequest) HasOperation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MutateObjectRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *MutateObjectRequest) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MutateObjectRequest) HasOldObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MutateObjectRequest) ClearOperation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Operation = Operation_OPERATION_UNSPECIFIED
}

func (x *MutateObjectRequest) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *MutateObjectRequest) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ObjectBytes = nil
}

func (x *MutateObjectRequest) ClearOldObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OldObjectBytes = nil
}

type MutateObjectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation is the requested operation.
	Operation *Operation
	// kind is the object kind.
	Kind *GroupVersionKind
	// object_bytes is the object in the request, including the full metadata envelope.
	ObjectBytes []byte
	// old_object_bytes is the object as it currently exists in storage,
	// including the full metadata envelope.
	OldObjectBytes []byte
}

func (b0 MutateObjectRequest_builder) Build() *MutateObjectRequest {
	m0 := &MutateObjectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Operation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Operation = *b.Operation
	}
	x.xxx_hidden_Kind = b.Kind
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	if b.OldObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OldObjectBytes = b.OldObjectBytes
	}
	return m0
}

// MutateAdmissionResponse returns a mutated copy of the object in a form that
// can be admitted.
type MutateObjectResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Allowed     bool                   `protobuf:"varint,1,opt,name=allowed"`
	xxx_hidden_Result      *StatusResult          `protobuf:"bytes,2,opt,name=result"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,3,rep,name=warnings"`
	xxx_hidden_ObjectBytes []byte                 `protobuf:"bytes,4,opt,name=object_bytes,json=objectBytes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MutateObjectResponse) Reset() {
	*x = MutateObjectResponse{}
	mi := &file_grafana_plugin_v3_mutate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateObjectResponse) ProtoMessage() {}

func (x *MutateObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_mutate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MutateObjectResponse) GetAllowed() bool {
	if x != nil {
		return x.xxx_hidden_Allowed
	}
	return false
}

func (x *MutateObjectResponse) GetResult() *StatusResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *MutateObjectResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *MutateObjectResponse) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *MutateObjectResponse) SetAllowed(v bool) {
	x.xxx_hidden_Allowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MutateObjectResponse) SetResult(v *StatusResult) {
	x.xxx_hidden_Result = v
}

func (x *MutateObjectResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *MutateObjectResponse) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *MutateObjectResponse) HasAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MutateObjectResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *MutateObjectResponse) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MutateObjectResponse) ClearAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Allowed = false
}

func (x *MutateObjectResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *MutateObjectResponse) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ObjectBytes = nil
}

type MutateObjectResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// allowed indicates whether or not the admission request was permitted.
	Allowed *bool
	// result contains extra detail about why an admission request was denied.
	// It is not consulted in any way when allowed is true.
	Result *StatusResult
	// warnings is a list of warning messages to return to the requesting client.
	Warnings []string
	// object_bytes is the mutated object.
	ObjectBytes []byte
}

func (b0 MutateObjectResponse_builder) Build() *MutateObjectResponse {
	m0 := &MutateObjectResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Allowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Allowed = *b.Allowed
	}
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Warnings = b.Warnings
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	return m0
}

var File_grafana_plugin_v3_mutate_proto protoreflect.FileDescriptor

const file_grafana_plugin_v3_mutate_proto_rawDesc = "" +
	"\n" +
	"\x1egrafana/plugin/v3/mutate.proto\x12\x11grafana.plugin.v3\x1a\x1egrafana/plugin/v3/common.proto\"\xd7\x01\n" +
	"\x13MutateObjectRequest\x12:\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1c.grafana.plugin.v3.OperationR\toperation\x127\n" +
	"\x04kind\x18\x02 \x01(\v2#.grafana.plugin.v3.GroupVersionKindR\x04kind\x12!\n" +
	"\fobject_bytes\x18\x03 \x01(\fR\vobjectBytes\x12(\n" +
	"\x10old_object_bytes\x18\x04 \x01(\fR\x0eoldObjectBytes\"\xa8\x01\n" +
	"\x14MutateObjectResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.grafana.plugin.v3.StatusResultR\x06result\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x12!\n" +
	"\fobject_bytes\x18\x04 \x01(\fR\vobjectBytes2p\n" +
	"\rMutateService\x12_\n" +
	"\fMutateObject\x12&.grafana.plugin.v3.MutateObjectRequest\x1a'.grafana.plugin.v3.MutateObjectResponseB\xde\x01\n" +
	"\x15com.grafana.plugin.v3B\vMutateProtoP\x01ZRgithub.com/grafana/grafana-app-sdk/plugin-next/genproto/grafana/plugin/v3;pluginv3\xa2\x02\x03GPX\xaa\x02\x11Grafana.Plugin.V3\xca\x02\x11Grafana\\Plugin\\V3\xe2\x02\x1dGrafana\\Plugin\\V3\\GPBMetadata\xea\x02\x13Grafana::Plugin::V3b\beditionsp\xe9\a"

var file_grafana_plugin_v3_mutate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grafana_plugin_v3_mutate_proto_goTypes = []any{
	(*MutateObjectRequest)(nil),  // 0: grafana.plugin.v3.MutateObjectRequest
	(*MutateObjectResponse)(nil), // 1: grafana.plugin.v3.MutateObjectResponse
	(Operation)(0),               // 2: grafana.plugin.v3.Operation
	(*GroupVersionKind)(nil),     // 3: grafana.plugin.v3.GroupVersionKind
	(*StatusResult)(nil),         // 4: grafana.plugin.v3.StatusResult
}
var file_grafana_plugin_v3_mutate_proto_depIdxs = []int32{
	2, // 0: grafana.plugin.v3.MutateObjectRequest.operation:type_name -> grafana.plugin.v3.Operation
	3, // 1: grafana.plugin.v3.MutateObjectRequest.kind:type_name -> grafana.plugin.v3.GroupVersionKind
	4, // 2: grafana.plugin.v3.MutateObjectResponse.result:type_name -> grafana.plugin.v3.StatusResult
	0, // 3: grafana.plugin.v3.MutateService.MutateObject:input_type -> grafana.plugin.v3.MutateObjectRequest
	1, // 4: grafana.plugin.v3.MutateService.MutateObject:output_type -> grafana.plugin.v3.MutateObjectResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grafana_plugin_v3_mutate_proto_init() }
func file_grafana_plugin_v3_mutate_proto_init() {
	if File_grafana_plugin_v3_mutate_proto != nil {
		return
	}
	file_grafana_plugin_v3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_plugin_v3_mutate_proto_rawDesc), len(file_grafana_plugin_v3_mutate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grafana_plugin_v3_mutate_proto_goTypes,
		DependencyIndexes: file_grafana_plugin_v3_mutate_proto_depIdxs,
		MessageInfos:      file_grafana_plugin_v3_mutate_proto_msgTypes,
	}.Build()
	File_grafana_plugin_v3_mutate_proto = out.File
	file_grafana_plugin_v3_mutate_proto_goTypes = nil
	file_grafana_plugin_v3_mutate_proto_depIdxs = nil
}
