// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/plugin/v3/status.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusResult carries a machine- and human-readable description of the outcome
// of an operation. It mirrors the Kubernetes meta/v1 Status shape:
// https://github.com/kubernetes/apimachinery/blob/v0.36.3/pkg/apis/meta/v1/generated.proto#L979
type StatusResult struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,2,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,3,opt,name=message"`
	xxx_hidden_Reason      *string                `protobuf:"bytes,4,opt,name=reason"`
	xxx_hidden_Details     *StatusDetails         `protobuf:"bytes,5,opt,name=details"`
	xxx_hidden_Code        int32                  `protobuf:"varint,6,opt,name=code"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatusResult) Reset() {
	*x = StatusResult{}
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResult) ProtoMessage() {}

func (x *StatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusResult) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *StatusResult) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *StatusResult) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *StatusResult) GetDetails() *StatusDetails {
	if x != nil {
		return x.xxx_hidden_Details
	}
	return nil
}

func (x *StatusResult) GetCode() int32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *StatusResult) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *StatusResult) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *StatusResult) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *StatusResult) SetDetails(v *StatusDetails) {
	x.xxx_hidden_Details = v
}

func (x *StatusResult) SetCode(v int32) {
	x.xxx_hidden_Code = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *StatusResult) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StatusResult) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StatusResult) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StatusResult) HasDetails() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Details != nil
}

func (x *StatusResult) HasCode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StatusResult) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *StatusResult) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *StatusResult) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Reason = nil
}

func (x *StatusResult) ClearDetails() {
	x.xxx_hidden_Details = nil
}

func (x *StatusResult) ClearCode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Code = 0
}

type StatusResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Status of the operation.
	// One of: "Success" or "Failure".
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
	// +optional
	Status *string
	// A human-readable description of the status of this operation.
	// +optional
	Message *string
	// A machine-readable description of why this operation is in the
	// "Failure" status. If this value is empty there
	// is no information available. A Reason clarifies an HTTP status
	// code but does not override it.
	// +optional
	Reason *string
	// Extended data associated with the reason.  Each reason may define its
	// own extended details. This field is optional and the data returned
	// is not guaranteed to conform to any schema except that defined by
	// the reason type.
	// +optional
	// +listType=atomic
	Details *StatusDetails
	// Suggested HTTP return code for this status, 0 if not set.
	// +optional
	Code *int32
}

func (b0 StatusResult_builder) Build() *StatusResult {
	m0 := &StatusResult{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Status = b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Message = b.Message
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Reason = b.Reason
	}
	x.xxx_hidden_Details = b.Details
	if b.Code != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Code = *b.Code
	}
	return m0
}

// StatusDetails is a set of additional properties that MAY be set by the
// server to provide additional information about a response. The Reason
// field of a Status object defines what attributes will be set. Clients
// must ignore fields that do not match the defined type of each attribute,
// and should assume that any attribute may be empty, invalid, or under
// defined.
type StatusDetails struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name              *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Group             *string                `protobuf:"bytes,2,opt,name=group"`
	xxx_hidden_Kind              *string                `protobuf:"bytes,3,opt,name=kind"`
	xxx_hidden_Uid               *string                `protobuf:"bytes,6,opt,name=uid"`
	xxx_hidden_Causes            *[]*StatusCause        `protobuf:"bytes,4,rep,name=causes"`
	xxx_hidden_RetryAfterSeconds int32                  `protobuf:"varint,5,opt,name=retry_after_seconds,json=retryAfterSeconds"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *StatusDetails) Reset() {
	*x = StatusDetails{}
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusDetails) ProtoMessage() {}

func (x *StatusDetails) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusDetails) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *StatusDetails) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *StatusDetails) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *StatusDetails) GetUid() string {
	if x != nil {
		if x.xxx_hidden_Uid != nil {
			return *x.xxx_hidden_Uid
		}
		return ""
	}
	return ""
}

func (x *StatusDetails) GetCauses() []*StatusCause {
	if x != nil {
		if x.xxx_hidden_Causes != nil {
			return *x.xxx_hidden_Causes
		}
	}
	return nil
}

func (x *StatusDetails) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_RetryAfterSeconds
	}
	return 0
}

func (x *StatusDetails) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *StatusDetails) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *StatusDetails) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *StatusDetails) SetUid(v string) {
	x.xxx_hidden_Uid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *StatusDetails) SetCauses(v []*StatusCause) {
	x.xxx_hidden_Causes = &v
}

func (x *StatusDetails) SetRetryAfterSeconds(v int32) {
	x.xxx_hidden_RetryAfterSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *StatusDetails) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StatusDetails) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StatusDetails) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StatusDetails) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StatusDetails) HasRetryAfterSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StatusDetails) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *StatusDetails) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Group = nil
}

func (x *StatusDetails) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Kind = nil
}

func (x *StatusDetails) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Uid = nil
}

func (x *StatusDetails) ClearRetryAfterSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_RetryAfterSeconds = 0
}

type StatusDetails_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name attribute of the resource associated with the status StatusReason
	// (when there is a single name which can be described).
	// +optional
	Name *string
	// The group attribute of the resource associated with the status StatusReason.
	// +optional
	Group *string
	// The kind attribute of the resource associated with the status StatusReason.
	// On some operations may differ from the requested resource Kind.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	// +optional
	Kind *string
	// UID of the resource.
	// (when there is a single resource which can be described).
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
	// +optional
	Uid *string
	// The Causes array includes more details associated with the StatusReason
	// failure. Not all StatusReasons may provide detailed causes.
	// +optional
	// +listType=atomic
	Causes []*StatusCause
	// If specified, the time in seconds before the operation should be retried. Some errors may indicate
	// the client must take an alternate action - for those errors this field may indicate how long to wait
	// before taking the alternate action.
	// +optional
	RetryAfterSeconds *int32
}

func (b0 StatusDetails_builder) Build() *StatusDetails {
	m0 := &StatusDetails{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Group = b.Group
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Kind = b.Kind
	}
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Uid = b.Uid
	}
	x.xxx_hidden_Causes = &b.Causes
	if b.RetryAfterSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_RetryAfterSeconds = *b.RetryAfterSeconds
	}
	return m0
}

// StatusCause provides more information about an api.Status failure, including
// cases when multiple errors are encountered.
type StatusCause struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Reason      *string                `protobuf:"bytes,1,opt,name=reason"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	xxx_hidden_Field       *string                `protobuf:"bytes,3,opt,name=field"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StatusCause) Reset() {
	*x = StatusCause{}
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCause) ProtoMessage() {}

func (x *StatusCause) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatusCause) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *StatusCause) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *StatusCause) GetField() string {
	if x != nil {
		if x.xxx_hidden_Field != nil {
			return *x.xxx_hidden_Field
		}
		return ""
	}
	return ""
}

func (x *StatusCause) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *StatusCause) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *StatusCause) SetField(v string) {
	x.xxx_hidden_Field = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *StatusCause) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StatusCause) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StatusCause) HasField() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StatusCause) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Reason = nil
}

func (x *StatusCause) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

func (x *StatusCause) ClearField() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Field = nil
}

type StatusCause_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A machine-readable description of the cause of the error. If this value is
	// empty there is no information available.
	// +optional
	Reason *string
	// A human-readable description of the cause of the error.  This field may be
	// presented as-is to a reader.
	// +optional
	Message *string
	// The field of the resource that has caused this error, as named by its JSON
	// serialization. May include dot and postfix notation for nested attributes.
	// Arrays are zero-indexed.  Fields may appear more than once in an array of
	// causes due to fields having multiple errors.
	// Optional.
	//
	// Examples:
	//
	//	"name" - the field "name" on the current resource
	//	"items[0].name" - the field "name" on the first array entry in "items"
	//
	// +optional
	Field *string
}

func (b0 StatusCause_builder) Build() *StatusCause {
	m0 := &StatusCause{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Reason = b.Reason
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Message = b.Message
	}
	if b.Field != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Field = b.Field
	}
	return m0
}

var File_grafana_plugin_v3_status_proto protoreflect.FileDescriptor

const file_grafana_plugin_v3_status_proto_rawDesc = "" +
	"\n" +
	"\x1egrafana/plugin/v3/status.proto\x12\x11grafana.plugin.v3\"\xa8\x01\n" +
	"\fStatusResult\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12:\n" +
	"\adetails\x18\x05 \x01(\v2 .grafana.plugin.v3.StatusDetailsR\adetails\x12\x12\n" +
	"\x04code\x18\x06 \x01(\x05R\x04code\"\xc7\x01\n" +
	"\rStatusDetails\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\tR\x03uid\x126\n" +
	"\x06causes\x18\x04 \x03(\v2\x1e.grafana.plugin.v3.StatusCauseR\x06causes\x12.\n" +
	"\x13retry_after_seconds\x18\x05 \x01(\x05R\x11retryAfterSeconds\"U\n" +
	"\vStatusCause\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05fieldB\xde\x01\n" +
	"\x15com.grafana.plugin.v3B\vStatusProtoP\x01ZRgithub.com/grafana/grafana-app-sdk/plugin-next/genproto/grafana/plugin/v3;pluginv3\xa2\x02\x03GPX\xaa\x02\x11Grafana.Plugin.V3\xca\x02\x11Grafana\\Plugin\\V3\xe2\x02\x1dGrafana\\Plugin\\V3\\GPBMetadata\xea\x02\x13Grafana::Plugin::V3b\beditionsp\xe9\a"

var file_grafana_plugin_v3_status_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grafana_plugin_v3_status_proto_goTypes = []any{
	(*StatusResult)(nil),  // 0: grafana.plugin.v3.StatusResult
	(*StatusDetails)(nil), // 1: grafana.plugin.v3.StatusDetails
	(*StatusCause)(nil),   // 2: grafana.plugin.v3.StatusCause
}
var file_grafana_plugin_v3_status_proto_depIdxs = []int32{
	1, // 0: grafana.plugin.v3.StatusResult.details:type_name -> grafana.plugin.v3.StatusDetails
	2, // 1: grafana.plugin.v3.StatusDetails.causes:type_name -> grafana.plugin.v3.StatusCause
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grafana_plugin_v3_status_proto_init() }
func file_grafana_plugin_v3_status_proto_init() {
	if File_grafana_plugin_v3_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_plugin_v3_status_proto_rawDesc), len(file_grafana_plugin_v3_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grafana_plugin_v3_status_proto_goTypes,
		DependencyIndexes: file_grafana_plugin_v3_status_proto_depIdxs,
		MessageInfos:      file_grafana_plugin_v3_status_proto_msgTypes,
	}.Build()
	File_grafana_plugin_v3_status_proto = out.File
	file_grafana_plugin_v3_status_proto_goTypes = nil
	file_grafana_plugin_v3_status_proto_depIdxs = nil
}
