// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grafana/plugin/v3/validate.proto

package pluginv3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidateService_ValidateObject_FullMethodName = "/grafana.plugin.v3.ValidateService/ValidateObject"
)

// ValidateServiceClient is the client API for ValidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/admission/types.go#L41
type ValidateServiceClient interface {
	// ValidateObject validates a resource; the response is a simple yes/no.
	ValidateObject(ctx context.Context, in *ValidateObjectRequest, opts ...grpc.CallOption) (*ValidateObjectResponse, error)
}

type validateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidateServiceClient(cc grpc.ClientConnInterface) ValidateServiceClient {
	return &validateServiceClient{cc}
}

func (c *validateServiceClient) ValidateObject(ctx context.Context, in *ValidateObjectRequest, opts ...grpc.CallOption) (*ValidateObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateObjectResponse)
	err := c.cc.Invoke(ctx, ValidateService_ValidateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ValidateServiceServer is the server API for ValidateService service.
// All implementations should embed UnimplementedValidateServiceServer
// for forward compatibility.
//
// AdmissionService is based on the Kubernetes admission webhook pattern.
// It can be used to verify that objects are valid and to mutate them.
// See: https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/admission/types.go#L41
type ValidateServiceServer interface {
	// ValidateObject validates a resource; the response is a simple yes/no.
	ValidateObject(context.Context, *ValidateObjectRequest) (*ValidateObjectResponse, error)
}

// UnimplementedValidateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidateServiceServer struct{}

func (UnimplementedValidateServiceServer) ValidateObject(context.Context, *ValidateObjectRequest) (*ValidateObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateObject not implemented")
}
func (UnimplementedValidateServiceServer) testEmbeddedByValue() {}

// UnsafeValidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidateServiceServer will
// result in compilation errors.
type UnsafeValidateServiceServer interface {
	mustEmbedUnimplementedValidateServiceServer()
}

func RegisterValidateServiceServer(s grpc.ServiceRegistrar, srv ValidateServiceServer) {
	// If the following call panics, it indicates UnimplementedValidateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidateService_ServiceDesc, srv)
}

func _ValidateService_ValidateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidateServiceServer).ValidateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidateService_ValidateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidateServiceServer).ValidateObject(ctx, req.(*ValidateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ValidateService_ServiceDesc is the grpc.ServiceDesc for ValidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.v3.ValidateService",
	HandlerType: (*ValidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateObject",
			Handler:    _ValidateService_ValidateObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grafana/plugin/v3/validate.proto",
}
