//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha3

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaAppRoute = resource.NewSimpleSchema("apps.grafana.app", "v1alpha3", NewAppRoute(), &AppRouteList{}, resource.WithKind("AppRoute"),
		resource.WithPlural("approutes"), resource.WithScope(resource.ClusterScope))
	kindAppRoute = resource.Kind{
		Schema: schemaAppRoute,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &AppRouteJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func AppRouteKind() resource.Kind {
	return kindAppRoute
}

// Schema returns a resource.SimpleSchema representation of AppRoute
func AppRouteSchema() *resource.SimpleSchema {
	return schemaAppRoute
}

// Interface compliance checks
var _ resource.Schema = kindAppRoute
