//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha3

import (
	"fmt"
	"github.com/grafana/grafana-app-sdk/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"time"
)

// +k8s:openapi-gen=true
type AppRoute struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`

	// Spec is the spec of the AppRoute
	Spec AppRouteSpec `json:"spec" yaml:"spec"`

	Status AppRouteStatus `json:"status" yaml:"status"`
}

func NewAppRoute() *AppRoute {
	return &AppRoute{
		Spec:   *NewAppRouteSpec(),
		Status: *NewAppRouteStatus(),
	}
}

func (o *AppRoute) GetSpec() any {
	return o.Spec
}

func (o *AppRoute) SetSpec(spec any) error {
	cast, ok := spec.(AppRouteSpec)
	if !ok {
		return fmt.Errorf("cannot set spec type %#v, not of type Spec", spec)
	}
	o.Spec = cast
	return nil
}

func (o *AppRoute) GetSubresources() map[string]any {
	return map[string]any{
		"status": o.Status,
	}
}

func (o *AppRoute) GetSubresource(name string) (any, bool) {
	switch name {
	case "status":
		return o.Status, true
	default:
		return nil, false
	}
}

func (o *AppRoute) SetSubresource(name string, value any) error {
	switch name {
	case "status":
		cast, ok := value.(AppRouteStatus)
		if !ok {
			return fmt.Errorf("cannot set status type %#v, not of type AppRouteStatus", value)
		}
		o.Status = cast
		return nil
	default:
		return fmt.Errorf("subresource '%s' does not exist", name)
	}
}

func (o *AppRoute) GetStaticMetadata() resource.StaticMetadata {
	gvk := o.GroupVersionKind()
	return resource.StaticMetadata{
		Name:      o.ObjectMeta.Name,
		Namespace: o.ObjectMeta.Namespace,
		Group:     gvk.Group,
		Version:   gvk.Version,
		Kind:      gvk.Kind,
	}
}

func (o *AppRoute) SetStaticMetadata(metadata resource.StaticMetadata) {
	o.Name = metadata.Name
	o.Namespace = metadata.Namespace
	o.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   metadata.Group,
		Version: metadata.Version,
		Kind:    metadata.Kind,
	})
}

func (o *AppRoute) GetCommonMetadata() resource.CommonMetadata {
	dt := o.DeletionTimestamp
	var deletionTimestamp *time.Time
	if dt != nil {
		deletionTimestamp = &dt.Time
	}
	// Legacy ExtraFields support
	extraFields := make(map[string]any)
	if o.Annotations != nil {
		extraFields["annotations"] = o.Annotations
	}
	if o.ManagedFields != nil {
		extraFields["managedFields"] = o.ManagedFields
	}
	if o.OwnerReferences != nil {
		extraFields["ownerReferences"] = o.OwnerReferences
	}
	return resource.CommonMetadata{
		UID:               string(o.UID),
		ResourceVersion:   o.ResourceVersion,
		Generation:        o.Generation,
		Labels:            o.Labels,
		CreationTimestamp: o.CreationTimestamp.Time,
		DeletionTimestamp: deletionTimestamp,
		Finalizers:        o.Finalizers,
		UpdateTimestamp:   o.GetUpdateTimestamp(),
		CreatedBy:         o.GetCreatedBy(),
		UpdatedBy:         o.GetUpdatedBy(),
		ExtraFields:       extraFields,
	}
}

func (o *AppRoute) SetCommonMetadata(metadata resource.CommonMetadata) {
	o.UID = types.UID(metadata.UID)
	o.ResourceVersion = metadata.ResourceVersion
	o.Generation = metadata.Generation
	o.Labels = metadata.Labels
	o.CreationTimestamp = metav1.NewTime(metadata.CreationTimestamp)
	if metadata.DeletionTimestamp != nil {
		dt := metav1.NewTime(*metadata.DeletionTimestamp)
		o.DeletionTimestamp = &dt
	} else {
		o.DeletionTimestamp = nil
	}
	o.Finalizers = metadata.Finalizers
	if o.Annotations == nil {
		o.Annotations = make(map[string]string)
	}
	if !metadata.UpdateTimestamp.IsZero() {
		o.SetUpdateTimestamp(metadata.UpdateTimestamp)
	}
	if metadata.CreatedBy != "" {
		o.SetCreatedBy(metadata.CreatedBy)
	}
	if metadata.UpdatedBy != "" {
		o.SetUpdatedBy(metadata.UpdatedBy)
	}
	// Legacy support for setting Annotations, ManagedFields, and OwnerReferences via ExtraFields
	if metadata.ExtraFields != nil {
		if annotations, ok := metadata.ExtraFields["annotations"]; ok {
			if cast, ok := annotations.(map[string]string); ok {
				o.Annotations = cast
			}
		}
		if managedFields, ok := metadata.ExtraFields["managedFields"]; ok {
			if cast, ok := managedFields.([]metav1.ManagedFieldsEntry); ok {
				o.ManagedFields = cast
			}
		}
		if ownerReferences, ok := metadata.ExtraFields["ownerReferences"]; ok {
			if cast, ok := ownerReferences.([]metav1.OwnerReference); ok {
				o.OwnerReferences = cast
			}
		}
	}
}

func (o *AppRoute) GetCreatedBy() string {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	return o.ObjectMeta.Annotations["grafana.com/createdBy"]
}

func (o *AppRoute) SetCreatedBy(createdBy string) {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	o.ObjectMeta.Annotations["grafana.com/createdBy"] = createdBy
}

func (o *AppRoute) GetUpdateTimestamp() time.Time {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	parsed, _ := time.Parse(time.RFC3339, o.ObjectMeta.Annotations["grafana.com/updateTimestamp"])
	return parsed
}

func (o *AppRoute) SetUpdateTimestamp(updateTimestamp time.Time) {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	o.ObjectMeta.Annotations["grafana.com/updateTimestamp"] = updateTimestamp.Format(time.RFC3339)
}

func (o *AppRoute) GetUpdatedBy() string {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	return o.ObjectMeta.Annotations["grafana.com/updatedBy"]
}

func (o *AppRoute) SetUpdatedBy(updatedBy string) {
	if o.ObjectMeta.Annotations == nil {
		o.ObjectMeta.Annotations = make(map[string]string)
	}

	o.ObjectMeta.Annotations["grafana.com/updatedBy"] = updatedBy
}

func (o *AppRoute) Copy() resource.Object {
	return resource.CopyObject(o)
}

func (o *AppRoute) DeepCopyObject() runtime.Object {
	return o.Copy()
}

func (o *AppRoute) DeepCopy() *AppRoute {
	cpy := &AppRoute{}
	o.DeepCopyInto(cpy)
	return cpy
}

func (o *AppRoute) DeepCopyInto(dst *AppRoute) {
	dst.TypeMeta.APIVersion = o.TypeMeta.APIVersion
	dst.TypeMeta.Kind = o.TypeMeta.Kind
	o.ObjectMeta.DeepCopyInto(&dst.ObjectMeta)
	o.Spec.DeepCopyInto(&dst.Spec)
	o.Status.DeepCopyInto(&dst.Status)
}

func (AppRoute) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.app.appmanifest.v1alpha3.AppRoute"
}

// Interface compliance compile-time check
var _ resource.Object = &AppRoute{}

// +k8s:openapi-gen=true
type AppRouteList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []AppRoute `json:"items" yaml:"items"`
}

func (o *AppRouteList) DeepCopyObject() runtime.Object {
	return o.Copy()
}

func (o *AppRouteList) Copy() resource.ListObject {
	cpy := &AppRouteList{
		TypeMeta: o.TypeMeta,
		Items:    make([]AppRoute, len(o.Items)),
	}
	o.ListMeta.DeepCopyInto(&cpy.ListMeta)
	for i := 0; i < len(o.Items); i++ {
		if item, ok := o.Items[i].Copy().(*AppRoute); ok {
			cpy.Items[i] = *item
		}
	}
	return cpy
}

func (o *AppRouteList) GetItems() []resource.Object {
	items := make([]resource.Object, len(o.Items))
	for i := 0; i < len(o.Items); i++ {
		items[i] = &o.Items[i]
	}
	return items
}

func (o *AppRouteList) SetItems(items []resource.Object) {
	o.Items = make([]AppRoute, len(items))
	for i := 0; i < len(items); i++ {
		o.Items[i] = *items[i].(*AppRoute)
	}
}

func (o *AppRouteList) DeepCopy() *AppRouteList {
	cpy := &AppRouteList{}
	o.DeepCopyInto(cpy)
	return cpy
}

func (o *AppRouteList) DeepCopyInto(dst *AppRouteList) {
	resource.CopyObjectInto(dst, o)
}

func (AppRouteList) OpenAPIModelName() string {
	return "com.github.grafana.grafana-app-sdk.app.appmanifest.v1alpha3.AppRouteList"
}

// Interface compliance compile-time check
var _ resource.ListObject = &AppRouteList{}

// Copy methods for all subresource types

// DeepCopy creates a full deep copy of Spec
func (s *AppRouteSpec) DeepCopy() *AppRouteSpec {
	cpy := &AppRouteSpec{}
	s.DeepCopyInto(cpy)
	return cpy
}

// DeepCopyInto deep copies Spec into another Spec object
func (s *AppRouteSpec) DeepCopyInto(dst *AppRouteSpec) {
	resource.CopyObjectInto(dst, s)
}

// DeepCopy creates a full deep copy of AppRouteStatus
func (s *AppRouteStatus) DeepCopy() *AppRouteStatus {
	cpy := &AppRouteStatus{}
	s.DeepCopyInto(cpy)
	return cpy
}

// DeepCopyInto deep copies AppRouteStatus into another AppRouteStatus object
func (s *AppRouteStatus) DeepCopyInto(dst *AppRouteStatus) {
	resource.CopyObjectInto(dst, s)
}
