//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha3

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaRouteBackend = resource.NewSimpleSchema("apps.grafana.app", "v1alpha3", NewRouteBackend(), &RouteBackendList{}, resource.WithKind("RouteBackend"),
		resource.WithPlural("routebackends"), resource.WithScope(resource.ClusterScope))
	kindRouteBackend = resource.Kind{
		Schema: schemaRouteBackend,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &RouteBackendJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func RouteBackendKind() resource.Kind {
	return kindRouteBackend
}

// Schema returns a resource.SimpleSchema representation of RouteBackend
func RouteBackendSchema() *resource.SimpleSchema {
	return schemaRouteBackend
}

// Interface compliance checks
var _ resource.Schema = kindRouteBackend
