//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v1alpha3

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaRuntimeConfig = resource.NewSimpleSchema("apps.grafana.app", "v1alpha3", NewRuntimeConfig(), &RuntimeConfigList{}, resource.WithKind("RuntimeConfig"),
		resource.WithPlural("runtimeconfigs"), resource.WithScope(resource.ClusterScope))
	kindRuntimeConfig = resource.Kind{
		Schema: schemaRuntimeConfig,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &RuntimeConfigJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func RuntimeConfigKind() resource.Kind {
	return kindRuntimeConfig
}

// Schema returns a resource.SimpleSchema representation of RuntimeConfig
func RuntimeConfigSchema() *resource.SimpleSchema {
	return schemaRuntimeConfig
}

// Interface compliance checks
var _ resource.Schema = kindRuntimeConfig
