name: Build Main

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    # make test
    - name: Test
      run: go test -v ./...
    # make test
    - name: Test CLI module
      run: go test -v ./cmd/grafana-app-sdk/...
    # make test
    - name: Test plugin module
      run: go test -v ./plugin/...
  build:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    # make build
    - name: Build
      run: go build -v cmd/grafana-app-sdk/*.go
