name: Build Main

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    # make test
    - name: Test
      run: go test -v ./...
  build:
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Go env
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    # Preflight checks
    - name: Preflight checks
      run: make check-go-version
    # make build
    - name: Build
      run: go build -v cmd/grafana-app-sdk/*.go
