name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
  release:
    permissions:
      contents: write
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
    # git checkout
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        fetch-depth: 0
        persist-credentials: false
    # Go env
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: 'go.mod'
        cache: false
    # Release
    - name: Create Release
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
